In [2]:
import pandas as pd

In [2]:
df = pd.read_json("./PoliResult/out/decompose/final0_start_10_sample_llama-7b_decompose_fewshot_V1.0.json")
df

,id,label,claim,response,context,justification
0,###98,FALSE,The United Nations plans to implant everyone w...,"[{'role': 'assistant', 'content': 'Here are th...",What’s more wild than science fiction’s robots...,This theory is an overreach of a system the Un...
1,###44,TRUE,The Machinists Union does not (support the USM...,"[{'role': 'assistant', 'content': 'Here are th...",In the last debate before the Feb. 3 Iowa pres...,"Sanders said about supporting USMCA, ""The AFL-..."
2,###62,FALSE,Gov. Tony Evers proposed raising taxes on the ...,"[{'role': 'assistant', 'content': 'Here are th...",Wisconsin's struggling farms were front and ce...,Nygren said the governor proposed raising taxe...
3,###24,TRUE,"If you're a black woman, you're 320% more like...","[{'role': 'assistant', 'content': 'Here are th...",In an exchange about racial inequality at Dece...,Yang said black women are 320% more likely to ...
4,###102,FALSE,Left-wing activist John Sullivan incited (the)...,"[{'role': 'assistant', 'content': 'Here are th...","UPDATE, Jan. 15, 2021: Following the publicati...","A Facebook post claimed Sullivan ""incited (the..."
5,###37,TRUE,Mike Bloomberg is a candidate who in 2015 stat...,"[{'role': 'assistant', 'content': 'Here are th...",U.S. Sen. Bernie Sanders welcomed Democratic r...,Sanders quoted Bloomberg as saying in 2015 tha...
6,###83,FALSE,The impeachment process against Donald Trump p...,"[{'role': 'assistant', 'content': 'Here are th...",Republicans explained their party-line vote ag...,"Cole said the impeachment process ""provides fe..."
7,###7,TRUE,You have literally 140 people dying every day ...,"[{'role': 'assistant', 'content': 'Here are th...",As cases of opioid use disorder continue to wr...,"""You have literally 140 people dying every day..."
8,###113,FALSE,The CDC finally admits its COVID-19 test can’t...,"[{'role': 'assistant', 'content': 'Here are th...","This past summer, many social media posts clai...",An Instagram post claims that the CDC is withd...
9,###51,HALF TRUE,I have also overseen historic funding increase...,"[{'role': 'assistant', 'content': 'Here are th...",President Donald Trump told Congress during hi...,"Trump said, ""I have also overseen historic fun..."
10,###40,HALF TRUE,Marijuana has a unique impact on the developin...,"[{'role': 'assistant', 'content': 'Here are th...",Speaking about a recent federal advisory on ma...,Speaking about the risks associated with marij...

In [12]:
df.loc[0, 'response'][0]['content']

'Here are the necessary questions to verify the claims:\n\n**Claim 1: Elizabeth Warren**\n\n1. What specific research or study did Elizabeth Warren conduct on the relationship between medical debt and bankruptcy?\n2. Can you provide the exact quote or source where Warren made this claim?\n3. What was the time period of Warren\'s research, and how does it relate to the current claim?\n4. Has there been any change in health insurance policies or laws between Warren\'s research period and the current date that could affect the claim?\n5. Can you provide the exact number of families that ended up in bankruptcy after a serious medical problem having health insurance, as per Warren\'s claim?\n6. Are there any other sources or studies that support or contradict Warren\'s claim?\n7. How does Warren\'s claim relate to the broader issue of medical debt and bankruptcy in the US?\n\n**Claim 2: Donald Trump**\n\n1. What does "lifted off of welfare" concretely mean in the context of Trump\'s claim?\n2. Can you provide the exact source or quote where Trump made this claim?\n3. Are there any restrictions or changes to welfare programs that could have led to the decrease in the number of people receiving benefits?\n4. How does the decrease in the number of people receiving benefits relate to changes made by Trump\'s administration?\n5. Are there any other sources or data that support or contradict Trump\'s claim?\n6. Can you provide the exact numbers of people who have been removed from food stamps and welfare programs, as per Trump\'s claim?\n7. How does Trump\'s claim relate to the broader issue of poverty and welfare in the US?\n\n**Claim 3: Brett McGurk**\n\n1. Can you provide the exact source or quote where McGurk made this claim?\n2. What does the Pentagon say about recent troop deployments to the Middle East region?\n3. From which countries did Trump remove troops, and what was the context of these removals?\n4. Which countries did Trump deploy new troops to, and what was the purpose of these deployments?\n5. Can you provide the most recent available data on troop distribution in countries in the Middle East?\n6. How does the increase in troop deployments relate to the resolution of conflicts in the Middle East?\n7. Are there any other sources or data that support or contradict McGurk\'s claim?\n\n**Claim 4: Facebook post about Michelle Lujan Grisham**\n\n1. Can you provide the exact source or quote where the Facebook post made this claim?\n2. What law regarding firearms did Governor Lujan Grisham support recently?\n3. Were guns seized from the governor\'s home, or from the officers who protect the governor?\n4. Can you provide any evidence or documentation that supports the claim?\n5. Are there any other sources or data that support or contradict the claim?\n6. How does the claim relate to the broader issue of gun control and firearms laws in New Mexico?\n7. Are there any other implications or consequences of the claim that need to be considered?\n\n**Claim 5: Dan Forest**\n\n1. Can you provide the exact source or quote where Forest made this claim?\n2. What is the enforcement policy of illegal immigration in North Carolina?\n3. Are there any records or data that support the claim that undocumented immigrants have victimized "tens of thousands" of children in North Carolina?\n4. Can you provide any evidence or documentation that supports the claim?\n5. Are there any other sources or data that support or contradict the claim?\n6. How does the claim relate to the broader issue of immigration and crime in North Carolina?\n7. Are there any other implications or consequences of the claim that need to be considered?\n\n**Claim 6: Bernie Sanders**\n\n1. Can you provide the exact source or quote where Sanders made this claim?\n2. What kind of support is Buttigieg supposedly receiving from Wall Street and the health care industry?\n3. Are there any hard numbers or data that support the claim?\n4. Did Pete Buttigieg receive a formal political endorsement from related players in the industry?\n5. Can you provide any evidence or documentation that supports the claim?\n6. How does the claim relate to the broader issue of campaign finance and industry influence in politics?\n7. Are there any other implications or consequences of the claim that need to be considered?\n\n**Claim 7: Bloggers about the United Nations**\n\n1. Can you provide the exact source or quote where the bloggers made this claim?\n2. What is the specific plan or proposal that the United Nations is supposedly implementing?\n3. Can you provide any evidence or documentation that supports the claim?\n4. Are there any other sources or data that support or contradict the claim?\n5. How does the claim relate to the broader issue of biometric ID and surveillance in the US?\n6. Are there any other implications or consequences of the claim that need to be considered?\n7. Can you provide any information about the credibility or reliability of the bloggers who made this claim?'

In [8]:
data= pd.read_csv("./data/Dataset_150.csv")
data.rename({'###_id':'TUD_ID'}, axis=1, inplace= True)
data['TUD_ID']= data['TUD_ID'].apply(lambda x: x.replace('###', 'TUD'))
data

,TUD_ID,article_id,statement,author,statement_date,full_claim,ruling_clean,ruling_clean_split,annotated_label,justification,journalist,novice
0,TUD98,17973.0,The United Nations plans to implant everyone w...,Speaker/Source: Bloggers,"February 20, 2020",The United Nations plans to implant everyone w...,"""What’s more wild than science fiction’s robot...",What’s more wild than science fiction’s robots...,FALSE,This theory is an overreach of a system the Un...,"Outside of the website truthandaction, has any...",What is the specific United Nations agency pla...
1,TUD44,17805.0,The Machinists Union does not (support the USM...,Speaker/Source: Bernie Sanders,"January 07, 2011",The Machinists Union does not (support the USM...,"""In the last debate before the Feb. 3 Iowa pre...",In the last debate before the Feb. 3 Iowa pres...,TRUE,"Sanders said about supporting USMCA, ""The AFL-...",[What is the USMCA trade deal?//What did Berni...,[Who is Bernie Sanders?//To what audience was ...
2,TUD62,179261.0,Gov. Tony Evers proposed raising taxes on the ...,Speaker/Source: John Nygren,"January 22, 2020",Gov. Tony Evers proposed raising taxes on the ...,"""Wisconsin's struggling farms were front and c...",Wisconsin's struggling farms were front and ce...,FALSE,Nygren said the governor proposed raising taxe...,[Does the Ag. Industry (AI) include small fami...,[What was the tax increase proposal? // Was th...
3,TUD24,176731.0,"If you're a black woman, you're 320% more like...",Speaker/Source: Andrew Yang,"December 19, 2019","If you're a black woman, you're 320% more like...","""In an exchange about racial inequality at Dec...",In an exchange about racial inequality at Dece...,TRUE,Yang said black women are 320% more likely to ...,How similar are Sanders and Yang's figures whe...,What type of complications did these black wom...
4,TUD102,NaN,Left-wing activist John Sullivan incited (the)...,Speaker/Source: Facebook posts,"January 7, 2021",Left-wing activist John Sullivan incited (the)...,"UPDATE, Jan. 15, 2021: Following the publicati...","UPDATE, Jan. 15, 2021: Following the publicati...",FALSE,"A Facebook post claimed Sullivan ""incited (the...",[If the affidavit says Sullivan did not led th...,[How credible is this information?'//' What is...
...,...,...,...,...,...,...,...,...,...,...,...,...
145,TUD67,175451.0,Confederate veterans were conferred with many ...,Speaker/Source: Sid Miller,"November 09, 2019",Confederate veterans were conferred with many ...,"""Texas Agriculture Commissioner Sid Miller wad...",Texas Agriculture Commissioner Sid Miller wade...,TRUE,"Miller said: ""Confederate veterans were confer...",[Who was involved in this debate? // What was ...,[What data about military benefits bestowed in...
146,TUD117,NaN,Electromagnetic radiation from wireless techno...,Speaker/Source: Bloggers,"December 17, 2021",Electromagnetic radiation from wireless techno...,"Since the beginning of the pandemic, various a...","Since the beginning of the pandemic, various a...",FALSE,A blog post claims that a study found clear ev...,[Where did these claims originate? // Have pos...,[Does electromagnetic radiation affect human h...
147,TUD47,178661.0,"Over the past two years, climate and weather d...",Speaker/Source: Tammy Baldwin,"December 10, 2019","Over the past two years, climate and weather d...","""When it comes to weather and climate change, ...","When it comes to weather and climate change, t...",TRUE,"Baldwin said ""Over the past two years, climate...",[Do these statistics reflect the general conse...,[What exactly is climate and weather disaster ...
148,TUD153,NaN,"One in eight American adults, or 12.7 percent ...",Speaker/Source: Richard Ojeda,"October 19, 2019","One in eight American adults, or 12.7 percent ...","Richard Ojeda, the former West Virginia legisl...","Richard Ojeda, the former West Virginia legisl...",HALF TRUE,"Ojeda tweeted, ""One in eight American adults, ...",Can you provide details from any recent journa...,Was a survey created and past around a certain...
149,TUD154,NaN,California is leading the nation in holding dr...,Speaker/Source: Gavin Newsom,"April 17, 2019",California is leading the nation in holding dr...,California regularly portrays itself as a nati...,California regularly portrays itself as a nati...,HALF TRUE,"Newsom said ""California is leading the nation ...",What was the question that Newsom was respondi...,Which drug companies specifically? // How are ...

In [9]:
data.to_csv("./data/Dataset_150.csv")

In [4]:
df1= pd.read_json(f"./PoliResult/out/decompose/coref0_start_150_sample_llama-8b_decompose_fewshot_V1.0.json")
s=df1.loc[0, 'response']

ValueError: Expected object or value

In [12]:
s1=s.split("**\n\n")[-1]
s1.split('\n')

['1. Can you provide the exact quote or source where the bloggers made this claim?',
 "2. What specific data or study do the bloggers rely on to make this claim about the United Nations' plans for biometric IDs?",
 '3. Are there any other factors that might have contributed to the alleged plan, such as changes in international cooperation or technological advancements?',
 "4. Can you provide the exact numbers of people who would be affected by the alleged plan, as per the bloggers' claim?",
 '5. Are there any records or data that show the reasons why the United Nations might have planned to implement biometric IDs?',
 "6. How does the United Nations' official stance on biometric IDs compare to the claim made in the Facebook post?"]

In [2]:
import pandas as pd
dt= pd.read_csv("./data/datetime.csv")
print(len(dt))

150

In [1]:
import tqdm
import json

In [23]:
df= pd.read_csv(f"./PoliResult/out/decompose/coref0_start_150_sample_llama-8b_decompose_fewshot_V1.0.csv")
#df.to_json(f"./PoliResult/out/decompose/coref0_start_150_sample_llama-8b_decompose_fewshot_V1.0.json")
with open(f"./PoliResult/out/decompose/final0_start_150_sample_llama-8b_decompose_fewshot_V1.0.json") as fp:
    df1= json.load(fp)

type(df1)

list

In [24]:
for i in range(len(df)):
    coref_q=  (df.loc[i, 'coref_q']).split('\n')
    #print(coref_q)
    #break

    if df1[i]['id']== df.loc[i, 'id']:
        df1[i]['coref_q']= coref_q

In [29]:
with open(f"./PoliResult/out/decompose/final0_start_150_sample_llama-8b_decompose_fewshot_V1.0.json", "w") as fp:
    json.dump(df1, fp)

In [30]:
with open(f"./PoliResult/out/decompose/final0_start_150_sample_llama-8b_decompose_fewshot_V1.0.json") as fp:
    df1= json.load(fp)

df1[0]

{'id': 'TUD98',
 'label': 'FALSE',
 'claim': 'The United Nations plans to implant everyone with a biometric ID.\nSpeaker/Source: Bloggers\nDate: February 20, 2020',
 'response': 'Here are the necessary questions to verify each claim:\n\n**Claim 1: Elizabeth Warren**\n\n1. What specific research or study did Elizabeth Warren conduct on the relationship between medical debt and bankruptcy?\n2. Can you provide the exact quote or source where Warren made this claim?\n3. What time period was Warren studying the issue of medical debt and bankruptcy?\n4. How did Warren define "serious medical problem" and "health insurance" in her research?\n5. Has Warren\'s research been peer-reviewed or published in a reputable academic journal?\n6. Are there any other studies or data that support or contradict Warren\'s claim?\n7. What changes in health insurance policy between Warren\'s research period and the current time might affect the relationship between medical debt and bankruptcy?\n8. Can you provide the exact numbers of families that ended up in bankruptcy after a serious medical problem with health insurance, as per Warren\'s claim?\n\n**Claim 2: Donald Trump**\n\n1. What specific data or study does Trump rely on to make this claim about the number of people lifted off food stamps and welfare?\n2. Can you provide the exact quote or source where Trump made this claim?\n3. How does Trump define "lifted off of welfare" and "food stamps" in this context?\n4. Are there any other factors that might have contributed to the decrease in the number of people receiving these benefits, such as changes in eligibility requirements or economic trends?\n5. Can you provide the exact numbers of people who have been lifted off food stamps and welfare, as per Trump\'s claim?\n6. Are there any records or data that show the reasons why people have been removed from these programs?\n7. How does Trump\'s administration\'s policies on welfare and food stamps compare to previous administrations?\n\n**Claim 3: Brett McGurk**\n\n1. Can you provide the exact quote or source where McGurk made this claim?\n2. What specific data or study does McGurk rely on to make this claim about the number of troops deployed to the Middle East?\n3. How does McGurk define "endless wars" and "sending troops back into the region" in this context?\n4. Are there any other factors that might have contributed to the increase in troop deployments, such as changes in regional security threats or military strategies?\n5. Can you provide the exact numbers of troops deployed to the Middle East, as per McGurk\'s claim?\n6. Are there any records or data that show the reasons why troops were deployed to the Middle East?\n7. How does the Pentagon\'s official stance on troop deployments compare to McGurk\'s claim?\n\n**Claim 4: Facebook post about Michelle Lujan Grisham**\n\n1. Can you provide the exact quote or source where the Facebook post made this claim?\n2. What specific law or policy did Lujan Grisham support in the New Mexico Senate?\n3. Are there any records or data that show the guns were seized from the governor\'s home or from her guards and household?\n4. Can you provide the exact numbers of guns seized, as per the Facebook post\'s claim?\n5. How does Lujan Grisham\'s stance on gun control compare to the claim made in the Facebook post?\n\n**Claim 5: Dan Forest**\n\n1. Can you provide the exact quote or source where Forest made this claim?\n2. What specific data or study does Forest rely on to make this claim about the number of children victimized by immigrants?\n3. Are there any other factors that might have contributed to the alleged increase in child victimization, such as changes in reporting requirements or demographic trends?\n4. Can you provide the exact numbers of children victimized, as per Forest\'s claim?\n5. Are there any records or data that show the reasons why immigrants might have victimized children?\n6. How does Forest\'s stance on immigration compare to the claim made in the Facebook post?\n\n**Claim 6: Bernie Sanders**\n\n1. Can you provide the exact quote or source where Sanders made this claim?\n2. What specific data or study does Sanders rely on to make this claim about Pete Buttigieg\'s support from Wall Street and the health care industry?\n3. Are there any other factors that might have contributed to Buttigieg\'s fundraising success, such as changes in campaign strategy or demographic trends?\n4. Can you provide the exact numbers of Buttigieg\'s fundraising from Wall Street and the health care industry, as per Sanders\' claim?\n5. Are there any records or data that show the reasons why Buttigieg received support from these industries?\n6. How does Sanders\' stance on campaign finance compare to the claim made in the Facebook post?\n\n**Claim 7: Bloggers about the United Nations**\n\n1. Can you provide the exact quote or source where the bloggers made this claim?\n2. What specific data or study do the bloggers rely on to make this claim about the United Nations\' plans for biometric IDs?\n3. Are there any other factors that might have contributed to the alleged plan, such as changes in international cooperation or technological advancements?\n4. Can you provide the exact numbers of people who would be affected by the alleged plan, as per the bloggers\' claim?\n5. Are there any records or data that show the reasons why the United Nations might have planned to implement biometric IDs?\n6. How does the United Nations\' official stance on biometric IDs compare to the claim made in the Facebook post?',
 'context': 'What’s more wild than science fiction’s robots, aliens and galaxies far, far away? The internet, that’s what. Word on the world wide web is that the United Nations is scheming to implant "everyone" with a "biometric ID." Say goodbye to your privacy. A story by website truthandaction claims that the United Nations is planning to have "all humans imprinted with biometric identification cards by 2030" as part of its "Global Goals agenda." No. The story was flagged as part of Facebook’s efforts to combat false news and misinformation on its News Feed. (Read more about our partnership with Facebook.)\nThis conspiracy theory is an overreach of a system that the UN is using to help identify refugees through biometrics that include facial recognition, fingerprints and iris scans. The truthandaction article points to the UN’s Global Goals initiative that was released in 2015. The agenda comprises 17 goals to achieve around the world by 2030 and includes objectives like no poverty, zero hunger and quality education. But the story zeroes in on a section of goal No. 16, which is called "Peace, justice and strong institutions." The section in question, 16.9, says: "By 2030, provide legal identity for all, including birth registration." The idea, though, was to help refugees prove their identities when seeking asylum, and biometrics refers to many different types of identification (not just microchips).\nAs part of the the UNs 2030 goal, companies Accenture and Microsoft unveiled a blockchain ID system prototype in 2017: It "combines a person`s biometric information such as their fingerprint or retina scan with blockchain, the record-keeping technology that underpins cryptocurrencies, to create a legal identity. When operational, the tool will provide refugees with the ability to present their IDs via an app on their smartphones at border crossings to prove they`re coming from a refugee camp and qualify for aid. The app will also enable displaced individuals to share their identities when required to access basic services such as education and healthcare."\nSince then, biometric technology has been developed to help identify refugee populations (though there have been some concerns about the practice). But the claim that the UN is planning to implant the world’s population with a microchip ID is far off. We found no mention of implanted microchips in the UN’s goals. Even if UN-backed biometric technology is aimed to expand beyond refugee and immigrant populations, this theory is based on speculation and overblows the facts.',
 'justification': 'This theory is an overreach of a system the United Nations uses to help identify refugees through biometrics that include facial recognition, fingerprints and iris scans. We rate this claim False.',
 'coref_q': ['Did the United Nations announce a plan to implant everyone with a biometric ID as claimed by bloggers on February 20, 2020?',
  'Can you provide the exact quote or source where bloggers claimed that the United Nations plans to implant everyone with a biometric ID on February 20, 2020?',
  'What specific data or study do bloggers rely on to make the claim that the United Nations plans to implant everyone with a biometric ID?',
  'Are there any other factors that might have contributed to the alleged plan by the United Nations to implant everyone with a biometric ID, such as changes in international cooperation or technological advancements?',
  "Can you provide the exact numbers of people who would be affected by the alleged United Nations plan to implant everyone with a biometric ID, as per the bloggers' claim made on February 20, 2020?",
  'Are there any records or data that show the reasons why the United Nations might have planned to implant everyone with a biometric ID, as claimed by bloggers on February 20, 2020?',
  "How does the United Nations' official stance on biometric IDs compare to the claim made by bloggers on February 20, 2020, that the United Nations plans to implant everyone with a biometric ID?",
  '']}

In [4]:
with open(f"./PoliResult/out/grounding/serp_150_sample_llama-8b_grounding_fewshot_V1.0.json") as fp:
    df1= json.load(fp)

df1[0]

{'id': 'TUD98',
 'label': 'FALSE',
 'claim': 'The United Nations plans to implant everyone with a biometric ID.\nSpeaker/Source: Bloggers\nDate: February 20, 2020',
 'response': 'Here are the necessary questions to verify each claim:\n\n**Claim 1: Elizabeth Warren**\n\n1. What specific research or study did Elizabeth Warren conduct on the relationship between medical debt and bankruptcy?\n2. Can you provide the exact quote or source where Warren made this claim?\n3. What time period was Warren studying the issue of medical debt and bankruptcy?\n4. How did Warren define "serious medical problem" and "health insurance" in her research?\n5. Has Warren\'s research been peer-reviewed or published in a reputable academic journal?\n6. Are there any other studies or data that support or contradict Warren\'s claim?\n7. What changes in health insurance policy between Warren\'s research period and the current time might affect the relationship between medical debt and bankruptcy?\n8. Can you provide the exact numbers of families that ended up in bankruptcy after a serious medical problem with health insurance, as per Warren\'s claim?\n\n**Claim 2: Donald Trump**\n\n1. What specific data or study does Trump rely on to make this claim about the number of people lifted off food stamps and welfare?\n2. Can you provide the exact quote or source where Trump made this claim?\n3. How does Trump define "lifted off of welfare" and "food stamps" in this context?\n4. Are there any other factors that might have contributed to the decrease in the number of people receiving these benefits, such as changes in eligibility requirements or economic trends?\n5. Can you provide the exact numbers of people who have been lifted off food stamps and welfare, as per Trump\'s claim?\n6. Are there any records or data that show the reasons why people have been removed from these programs?\n7. How does Trump\'s administration\'s policies on welfare and food stamps compare to previous administrations?\n\n**Claim 3: Brett McGurk**\n\n1. Can you provide the exact quote or source where McGurk made this claim?\n2. What specific data or study does McGurk rely on to make this claim about the number of troops deployed to the Middle East?\n3. How does McGurk define "endless wars" and "sending troops back into the region" in this context?\n4. Are there any other factors that might have contributed to the increase in troop deployments, such as changes in regional security threats or military strategies?\n5. Can you provide the exact numbers of troops deployed to the Middle East, as per McGurk\'s claim?\n6. Are there any records or data that show the reasons why troops were deployed to the Middle East?\n7. How does the Pentagon\'s official stance on troop deployments compare to McGurk\'s claim?\n\n**Claim 4: Facebook post about Michelle Lujan Grisham**\n\n1. Can you provide the exact quote or source where the Facebook post made this claim?\n2. What specific law or policy did Lujan Grisham support in the New Mexico Senate?\n3. Are there any records or data that show the guns were seized from the governor\'s home or from her guards and household?\n4. Can you provide the exact numbers of guns seized, as per the Facebook post\'s claim?\n5. How does Lujan Grisham\'s stance on gun control compare to the claim made in the Facebook post?\n\n**Claim 5: Dan Forest**\n\n1. Can you provide the exact quote or source where Forest made this claim?\n2. What specific data or study does Forest rely on to make this claim about the number of children victimized by immigrants?\n3. Are there any other factors that might have contributed to the alleged increase in child victimization, such as changes in reporting requirements or demographic trends?\n4. Can you provide the exact numbers of children victimized, as per Forest\'s claim?\n5. Are there any records or data that show the reasons why immigrants might have victimized children?\n6. How does Forest\'s stance on immigration compare to the claim made in the Facebook post?\n\n**Claim 6: Bernie Sanders**\n\n1. Can you provide the exact quote or source where Sanders made this claim?\n2. What specific data or study does Sanders rely on to make this claim about Pete Buttigieg\'s support from Wall Street and the health care industry?\n3. Are there any other factors that might have contributed to Buttigieg\'s fundraising success, such as changes in campaign strategy or demographic trends?\n4. Can you provide the exact numbers of Buttigieg\'s fundraising from Wall Street and the health care industry, as per Sanders\' claim?\n5. Are there any records or data that show the reasons why Buttigieg received support from these industries?\n6. How does Sanders\' stance on campaign finance compare to the claim made in the Facebook post?\n\n**Claim 7: Bloggers about the United Nations**\n\n1. Can you provide the exact quote or source where the bloggers made this claim?\n2. What specific data or study do the bloggers rely on to make this claim about the United Nations\' plans for biometric IDs?\n3. Are there any other factors that might have contributed to the alleged plan, such as changes in international cooperation or technological advancements?\n4. Can you provide the exact numbers of people who would be affected by the alleged plan, as per the bloggers\' claim?\n5. Are there any records or data that show the reasons why the United Nations might have planned to implement biometric IDs?\n6. How does the United Nations\' official stance on biometric IDs compare to the claim made in the Facebook post?',
 'context': 'What’s more wild than science fiction’s robots, aliens and galaxies far, far away? The internet, that’s what. Word on the world wide web is that the United Nations is scheming to implant "everyone" with a "biometric ID." Say goodbye to your privacy. A story by website truthandaction claims that the United Nations is planning to have "all humans imprinted with biometric identification cards by 2030" as part of its "Global Goals agenda." No. The story was flagged as part of Facebook’s efforts to combat false news and misinformation on its News Feed. (Read more about our partnership with Facebook.)\nThis conspiracy theory is an overreach of a system that the UN is using to help identify refugees through biometrics that include facial recognition, fingerprints and iris scans. The truthandaction article points to the UN’s Global Goals initiative that was released in 2015. The agenda comprises 17 goals to achieve around the world by 2030 and includes objectives like no poverty, zero hunger and quality education. But the story zeroes in on a section of goal No. 16, which is called "Peace, justice and strong institutions." The section in question, 16.9, says: "By 2030, provide legal identity for all, including birth registration." The idea, though, was to help refugees prove their identities when seeking asylum, and biometrics refers to many different types of identification (not just microchips).\nAs part of the the UNs 2030 goal, companies Accenture and Microsoft unveiled a blockchain ID system prototype in 2017: It "combines a person`s biometric information such as their fingerprint or retina scan with blockchain, the record-keeping technology that underpins cryptocurrencies, to create a legal identity. When operational, the tool will provide refugees with the ability to present their IDs via an app on their smartphones at border crossings to prove they`re coming from a refugee camp and qualify for aid. The app will also enable displaced individuals to share their identities when required to access basic services such as education and healthcare."\nSince then, biometric technology has been developed to help identify refugee populations (though there have been some concerns about the practice). But the claim that the UN is planning to implant the world’s population with a microchip ID is far off. We found no mention of implanted microchips in the UN’s goals. Even if UN-backed biometric technology is aimed to expand beyond refugee and immigrant populations, this theory is based on speculation and overblows the facts.',
 'justification': 'This theory is an overreach of a system the United Nations uses to help identify refugees through biometrics that include facial recognition, fingerprints and iris scans. We rate this claim False.',
 'coref_q': ['Did the United Nations announce a plan to implant everyone with a biometric ID as claimed by bloggers on February 20, 2020?',
  'Can you provide the exact quote or source where bloggers claimed that the United Nations plans to implant everyone with a biometric ID on February 20, 2020?',
  'What specific data or study do bloggers rely on to make the claim that the United Nations plans to implant everyone with a biometric ID?',
  'Are there any other factors that might have contributed to the alleged plan by the United Nations to implant everyone with a biometric ID, such as changes in international cooperation or technological advancements?',
  "Can you provide the exact numbers of people who would be affected by the alleged United Nations plan to implant everyone with a biometric ID, as per the bloggers' claim made on February 20, 2020?",
  'Are there any records or data that show the reasons why the United Nations might have planned to implant everyone with a biometric ID, as claimed by bloggers on February 20, 2020?',
  "How does the United Nations' official stance on biometric IDs compare to the claim made by bloggers on February 20, 2020, that the United Nations plans to implant everyone with a biometric ID?",
  ''],
 'published': '2020-02-20',
 'google_search': {'Did the United Nations announce a plan to implant everyone with a biometric ID as claimed by bloggers on February 20, 2020?': [{'title': 'Employee Privacy and RFID Microchips - The National Law Review',
    'link': 'https://natlawreview.com/article/chipping-away-employee-privacy-legal-implications-rfid-microchip-implants-employees',
    'snippet': "Since the FDA's approval, human microchip implantation has unsettled many, especially after news reports revealed that CityWatcher, a Massachusetts company, ...",
    'date': 'Oct 10, 2019',
    'attributes': {'Missing': 'announce everyone'},
    'position': 1},
   {'title': 'MIT Technology Review (@technologyreview) - Instagram',
    'link': 'https://www.instagram.com/technologyreview/?hl=en',
    'snippet': "Our in-depth reporting on innovation reveals and explains what's really happening now to help you know what's coming next.",
    'date': 'Dec 27, 2015',
    'attributes': {'Missing': 'announce ID claimed bloggers'},
    'position': 2},
   {'title': '[PDF] Federal Communications Commission FCC 16-148 1 Before the ...',
    'link': 'https://docs.fcc.gov/public/attachments/fcc-16-148a1.pdf',
    'snippet': 'By the Commission: Chairman Wheeler and Commissioner Rosenworcel issuing separate statements; Commissioner Clyburn approving in part, concurring in part and ...',
    'date': 'Nov 2, 2016',
    'position': 3},
   {'title': '[PDF] Joint logistics innovations - Defense Management Library',
    'link': 'https://dml.armywarcollege.edu/wp-content/uploads/2023/01/jfq-075.pdf',
    'snippet': 'United Nations.” Force, in this case, does not mean coercion, but the use of armed force as a tool of coercion or persuasion. Matthew Waxman notes that the ...',
    'date': 'Aug 29, 2014',
    'position': 4},
   {'title': '[PDF] THE WORLD TURNED UPSIDE DOWN: - The Aspen Institute',
    'link': 'https://www.aspeninstitute.org/wp-content/uploads/2017/11/FINAL-ASG-World-Upside-Down-FINAL.REV_.pdf',
    'snippet': "The Aspen Strategy Group (ASG) has spent more than thirty years bringing together a bipartisan group to reflect on the nation's most pressing international.",
    'date': 'Nov 30, 2017',
    'position': 5},
   {'title': '[PDF] White House Office of Science and Technology Policy',
    'link': 'https://obamawhitehouse.archives.gov/sites/default/files/microsites/ostp/OSTP-AI-RFI-Responses.pdf',
    'snippet': 'Initiatives focused on Java and the JVM will pave the way for AI to be implemented by large organizations in need of more accurate analytics. This includes ...',
    'date': 'Sep 1, 2016',
    'position': 6},
   {'title': '[PDF] The Promise of Digital Health: Addressing Non-communicable ...',
    'link': 'https://www.broadbandcommission.org/wp-content/uploads/2021/02/WGDigitalHealth_Report2018.pdf',
    'snippet': 'Digital health supports all stakeholders in combating the NCD burden by empowering patients to take care of their own health, enabling health workers to better ...',
    'date': 'Sep 23, 2018',
    'position': 7},
   {'title': '[PDF] Conceptualizing a Data Infrastructure for the Capture, Use, and ...',
    'link': 'https://www.healthit.gov/sites/default/files/onc_pghd_final_white_paper.pdf',
    'snippet': 'This white paper describes key opportunities and challenges and offers enabling actions that can further enhance PGHD capture, use, and sharing for health care ...',
    'date': 'Jan 23, 2018',
    'attributes': {'Missing': 'everyone | Show results with:everyone'},
    'position': 8},
   {'title': '[PDF] Medtech and the Internet of Medical Things How ... - Deloitte',
    'link': 'https://www2.deloitte.com/content/dam/Deloitte/global/Documents/Life-Sciences-Health-Care/gx-lshc-medtech-iomt-brochure.pdf',
    'snippet': 'The increasing numbers of connected medical devices and rising adoption of smartphones are expected to fuel the growth of the market still further.',
    'date': 'Jul 12, 2018',
    'attributes': {'Missing': 'everyone | Show results with:everyone'},
    'position': 9}],
  'Can you provide the exact quote or source where bloggers claimed that the United Nations plans to implant everyone with a biometric ID on February 20, 2020?': [{'title': '[PDF] Global Trends 2030: Alternative Worlds - DNI.gov',
    'link': 'https://www.dni.gov/files/documents/GlobalTrends_2030.pdf',
    'snippet': "Global Trends 2030: Alternative Worlds is the fifth installment in the National Intelligence. Council's series aimed at providing a framework for thinking ...",
    'date': 'Dec 10, 2012',
    'attributes': {'Missing': 'exact | Show results with:exact'},
    'position': 1},
   {'title': "When did Christians get the notion that 'The Mark Of The Beast ...",
    'link': 'https://www.quora.com/When-did-Christians-get-the-notion-that-The-Mark-Of-The-Beast-would-be-a-microchip',
    'snippet': 'When the idea of implantable electronics was first being worked on. Those who focus on the mark of the beast are majoring on the minors. They are focused on ...',
    'date': 'Feb 27, 2017',
    'attributes': {'Missing': 'United | Show results with:United'},
    'sitelinks': [{'title': 'What will phones look like in 20 years? - Quora',
      'link': 'https://www.quora.com/What-will-phones-look-like-in-20-years'},
     {'title': "What's the most innovative new idea that we can implement? - Quora",
      'link': 'https://www.quora.com/What%E2%80%99s-the-most-innovative-new-idea-that-we-can-implement'},
     {'title': 'How to easily test to make sure my RFID blocking wallet actually ...',
      'link': 'https://www.quora.com/How-can-I-easily-test-to-make-sure-my-RFID-blocking-wallet-actually-blocks-RFID-skimmers-etc'},
     {'title': 'If a child has been deaf since birth and they get a cochlear implant ...',
      'link': 'https://www.quora.com/If-a-child-has-been-deaf-since-birth-and-they-get-a-cochlear-implant-are-they-initially-frightened-to-hear-sounds'}],
    'position': 2},
   {'title': '[PDF] Federal Communications Commission FCC 16-148 1 Before the ...',
    'link': 'https://docs.fcc.gov/public/attachments/fcc-16-148a1.pdf',
    'snippet': 'By the Commission: Chairman Wheeler and Commissioner Rosenworcel issuing separate statements; Commissioner Clyburn approving in part, concurring in part and ...',
    'date': 'Nov 2, 2016',
    'position': 3},
   {'title': '[PDF] THE WORLD TURNED UPSIDE DOWN: - The Aspen Institute',
    'link': 'https://www.aspeninstitute.org/wp-content/uploads/2017/11/FINAL-ASG-World-Upside-Down-FINAL.REV_.pdf',
    'snippet': "The Aspen Strategy Group (ASG) has spent more than thirty years bringing together a bipartisan group to reflect on the nation's most pressing international.",
    'date': 'Nov 30, 2017',
    'position': 4},
   {'title': '[PDF] Fort Collins Police Services Policy Manual',
    'link': 'https://www.fcgov.com/police/pdf/policy_manual.pdf',
    'snippet': 'INTRODUCTION. This policy manual is the most current revision of the Fort Collins Police Services Policy. Manual and takes effect January 1, 2020.',
    'date': 'Jan 1, 2020',
    'attributes': {'Missing': 'everyone February'},
    'position': 5},
   {'title': '[PDF] USCC 2008 ANNUAL REPORT',
    'link': 'https://www.uscc.gov/sites/default/files/annual_reports/2008-Report-to-Congress-_0.pdf',
    'snippet': 'The Commission was created on October 30, 2000, by the Floyd D. Spence. National Defense Authorization Act for 2001 §1238, Pub. L. No. 106–398,. 114 STAT.',
    'date': 'Nov 17, 2008',
    'attributes': {'Missing': 'everyone biometric'},
    'position': 6},
   {'title': 'Understanding Cyber Conflict: 14 Analogies',
    'link': 'https://carnegieendowment.org/2017/10/16/understanding-cyber-conflict-14-analogies-pub-72689',
    'snippet': "Understanding Cyber Conflict draws lessons from past technological disruptions to inform and shape responses to today's cyber challenges.",
    'date': 'Oct 16, 2017',
    'position': 7},
   {'title': '[PDF] POLICY MANUAL | Tulsa Tech',
    'link': 'https://tulsatech.edu/policies/Tulsa-Tech-Policy-Manual_10-28-19.pdf',
    'snippet': 'the driver to provide positive identification. If the driver requests, the STT will provide positive identification. The STT will explain the testing procedure.',
    'date': 'Oct 28, 2019',
    'attributes': {'Missing': 'Nations everyone'},
    'position': 8},
   {'title': '[PDF] From vision to decision - Pharma 2020 - PwC',
    'link': 'https://www.pwc.com/gx/en/pharma-life-sciences/pharma2020/assets/pwc-pharma-success-strategies.pdf',
    'snippet': "We've outlined our vision of what lies ahead in previous Pharma 2020 papers. The theme of our latest paper is decisions: the decisions pharma companies will.",
    'date': 'Nov 20, 2012',
    'attributes': {'Missing': 'exact biometric'},
    'position': 9},
   {'title': '[PDF] The Global Technology Revolution 2020, In-Depth Analyses - RAND',
    'link': 'https://www.rand.org/content/dam/rand/pubs/technical_reports/2006/RAND_TR303.pdf',
    'snippet': "The National Intelligence Council (NIC) sponsored this study by The RAND Corporation to inform the NIC's 2020 project2 and help provide US policymakers with a ...",
    'date': 'May 27, 2005',
    'position': 10}],
  'What specific data or study do bloggers rely on to make the claim that the United Nations plans to implant everyone with a biometric ID?': [{'title': 'Employee Privacy and RFID Microchips - The National Law Review',
    'link': 'https://natlawreview.com/article/chipping-away-employee-privacy-legal-implications-rfid-microchip-implants-employees',
    'snippet': 'Having discussed the components of RFID microchips, we now understand their potential uses and focus on the use of RFID technology in the form of implantable ...',
    'date': 'Oct 10, 2019',
    'attributes': {'Missing': 'study | Show results with:study'},
    'position': 1},
   {'title': '[PDF] Unlocking Technology for the Global Goals - Www3.weforum.org.',
    'link': 'https://www3.weforum.org/docs/Unlocking_Technology_for_the_Global_Goals.pdf',
    'snippet': "Well-known examples include how to use data while ensuring people's right to privacy, protecting against the misuse of AI for crime or warfare, or to influence ...",
    'date': 'Jan 2, 2020',
    'position': 2},
   {'title': '[PDF] Council of Inspectors General on Integrity and Efficiency',

In [3]:
import json
with open(f"./PoliResult/out/decompose/final0_start_150_sample_llama-8b_decompose_fewshot_V1.0.json") as fp:
        dataset = json.load(fp)

In [6]:
import pandas as pd

d1= pd.read_pickle(f"./PoliResult/out/grounding/temp0_start_150_sample_llama-8b_grounded_fewshot_ruling_comments_V1.0_qaconstraint.pkl")
d1

,id,label,claim,response,context,justification,coref_q,grounded_answers
0,TUD98,FALSE,The United Nations plans to implant everyone w...,Here are the necessary questions to verify eac...,What’s more wild than science fiction’s robots...,This theory is an overreach of a system the Un...,[Did the United Nations announce a plan to imp...,"\nNo, the United Nations did not announce a pl..."
1,TUD44,TRUE,The Machinists Union does not (support the USM...,Here are the necessary questions to verify the...,In the last debate before the Feb. 3 Iowa pres...,"Sanders said about supporting USMCA, ""The AFL-...",[Did the Machinists Union and every environmen...,"\nNo, the Machinists Union and every environme..."
2,TUD62,FALSE,Gov. Tony Evers proposed raising taxes on the ...,Here are the necessary questions to verify the...,Wisconsin's struggling farms were front and ce...,Nygren said the governor proposed raising taxe...,[Did Governor Tony Evers propose raising taxes...,"\nAccording to the article, Governor Tony Ever..."
3,TUD24,TRUE,"If you're a black woman, you're 320% more like...",Here are the follow-up questions for each clai...,In an exchange about racial inequality at Dece...,Yang said black women are 320% more likely to ...,[What evidence supports Andrew Yang's claim ma...,"\nAccording to the article, the evidence that ..."
4,TUD102,FALSE,Left-wing activist John Sullivan incited (the)...,Here are the necessary questions to verify eac...,"UPDATE, Jan. 15, 2021: Following the publicati...","A Facebook post claimed Sullivan ""incited (the...",[Did left-wing activist John Sullivan incite t...,"\nAccording to the article, there is no conclu..."
...,...,...,...,...,...,...,...,...
145,TUD67,TRUE,Confederate veterans were conferred with many ...,Here are the necessary questions to verify the...,Texas Agriculture Commissioner Sid Miller wade...,"Miller said: ""Confederate veterans were confer...",[Did Acts of Congress in 1929 and 1957 confer ...,NaN
146,TUD117,FALSE,Electromagnetic radiation from wireless techno...,Here are the necessary questions to verify eac...,"Since the beginning of the pandemic, various a...",A blog post claims that a study found clear ev...,[Do electromagnetic radiation from wireless te...,NaN
147,TUD47,TRUE,"Over the past two years, climate and weather d...",Here are the necessary questions to verify the...,"When it comes to weather and climate change, t...","Baldwin said ""Over the past two years, climate...",[Did climate and weather disaster damage cost ...,NaN
148,TUD153,HALF TRUE,"One in eight American adults, or 12.7 percent ...",Here are the necessary questions to verify eac...,"Richard Ojeda, the former West Virginia legisl...","Ojeda tweeted, ""One in eight American adults, ...","[Did Richard Ojeda claim on October 19, 2019, ...",NaN
149,TUD154,HALF TRUE,California is leading the nation in holding dr...,Here are the necessary questions to verify eac...,California regularly portrays itself as a nati...,"Newsom said ""California is leading the nation ...",[Is California leading the nation in holding d...,NaN

In [7]:
d1.loc[0, 'grounded_answers']

'\nNo, the United Nations did not announce a plan to implant everyone with a biometric ID as claimed by bloggers. According to the article, the UN\'s goal is to provide legal identity for all, including birth registration, by 2030, as part of its "Peace, justice and strong institutions" initiative. However, this goal is aimed at helping refugees prove their identities when seeking asylum, and it does not involve implanting microchips.\nThe article does not mention a specific date, February 20, 2020, as the date when bloggers claimed that the United Nations plans to implant everyone with a biometric ID. However, it does mention that the story was flagged as part of Facebook\'s efforts to combat false news and misinformation on its News Feed, but it does not provide a specific date for this action.\n\nThe article does mention that the story was about a claim that the United Nations is planning to have "all humans imprinted with biometric identification cards by 2030" as part of its "Global Goals agenda." This claim was made by the website truthandaction.\nAccording to the article, bloggers rely on a story by the website truthandaction that points to the UN\'s Global Goals initiative, specifically goal No. 16, section 16.9, which says: "By 2030, provide legal identity for all, including birth registration."\nAccording to the article, there is no mention of any other factors that might have contributed to the alleged plan by the United Nations to implant everyone with a biometric ID. However, it does mention that biometric technology has been developed to help identify refugee populations since the UN-backed blockchain ID system prototype was unveiled in 2017. This development might have led to speculation about the expansion of biometric technology beyond refugee and immigrant populations.\nThe article does not mention any specific numbers of people who would be affected by the alleged United Nations plan to implant everyone with a biometric ID. It only mentions that the bloggers claim "everyone" would be affected.\nAccording to the article, there is no record or data that supports the claim that the United Nations planned to implant everyone with a biometric ID. In fact, the article states that the UN\'s goal is to provide legal identity for all, including birth registration, by 2030, as part of its 2030 agenda. This is stated in section 16.9 of the Global Goals initiative, which aims to help refugees prove their identities when seeking asylum. The article also mentions that the UN has developed a blockchain ID system prototype in 2017, which combines biometric information with blockchain technology to create a legal identity, but this is not about implanting microchips.\nAccording to the article, the United Nations\' official stance on biometric IDs is to help identify refugees through biometrics that include facial recognition, fingerprints, and iris scans, as part of its "Global Goals agenda." The UN\'s goal is to provide legal identity for all, including birth registration, by 2030, as stated in section 16.9 of the "Peace, justice and strong institutions" goal.\n\nIn contrast, the claim made by bloggers on February 20, 2020, is that the United Nations plans to implant "everyone" with a "biometric ID," which is an overreach of the UN\'s actual plan. The article states that there is no mention of implanted microchips in the UN\'s goals, and the UN\'s plan is to use biometric technology to help identify refugees and provide them with a legal identity, not to implant microchips in the general population.'

In [6]:
import json
import pandas as pd

d2= pd.read_json("./PoliResult/out/aggregate/final51_start_150_sample_llama-8b_aggregate_fewshot_V1.0.json")
d2.to_csv("./PoliResult/out/aggregate/final51_start_150_sample_llama-8b_aggregate_fewshot_V1.0.csv")

In [8]:
d3= pd.read_json("./PoliResult/out/aggregate/temp_150_sample_llama-8b_aggregate_fewshot_ruling_comments_V1.0.json")
d3.to_csv("./PoliResult/out/aggregate/temp_150_sample_llama-8b_aggregate_fewshot_ruling_comments_V1.0.csv")

In [9]:
d4=pd.read_json("./PoliResult/out/grounding/test/corpus_llama-8b_fewshot_V1.0.json")
d4.to_csv("./PoliResult/out/grounding/test/corpus_llama-8b_fewshot_V1.0.csv")

In [24]:
d5=pd.read_json("./PoliResult/out/grounding/serp_150_sample_gpt-4o_grounding_fewshot_V1.0.json")
d5.loc[0, 'google_search']

{'Has the United Nations officially announced any plans regarding biometric IDs for everyone?\n': [{'title': 'Digital identities in 2024 | DW Observatory',
   'link': 'https://dig.watch/topics/digital-identities',
   'snippet': 'Digital identities will gain relevance in 2024. The most interesting development will be related to the Digital Public Infrastructure (DPI) initiative.',
   'date': 'May 3, 2019',
   'attributes': {'Missing': 'everyone?'},
   'position': 1},
  {'title': '[PDF] Understanding the Lived Effects of Digital ID - The Engine Room',
   'link': 'https://digitalid.theengineroom.org/assets/pdfs/200123_FINAL_TER_Digital_ID_Report+Annexes_English_Interactive.pdf',
   'snippet': 'announced that they would have all government employees registered in a new biometric system by the end of the month.11 They plan to commission the ...',
   'date': 'Jan 25, 2020',
   'position': 2},
  {'title': 'Registration as an Identity Management Process - UNHCR',
   'link': 'https://www.unhcr.org/registration-guidance/chapter5/registration/',
   'snippet': "Biometrics are the preferred methodology for verifying an individual's identity, including at assistance delivery, as well as in the context of protection case ...",
   'date': 'Sep 21, 2018',
   'attributes': {'Missing': 'United Nations announced everyone?'},
   'position': 3},
  {'title': 'Digital identity: Contemporary challenges for data protection, privacy ...',
   'link': 'https://journals.sagepub.com/doi/full/10.1177/2053951719855091',
   'snippet': 'To tackle this crucial issue, the United Nations included the aim to provide legal identity for all by 2030 among the Sustainable Development Goals. Technology ...',
   'date': 'Jun 13, 2019',
   'attributes': {'Missing': 'announced | Show results with:announced'},
   'position': 4},
  {'title': '[PDF] THE IMPACT OF BIOMETRICS ON REFUGEES AND ASYLUM ...',
   'link': 'https://iow.eui.eu/wp-content/uploads/sites/18/2013/04/07-Rijpma-Background4-Refugees-and-Biometrics.pdf',
   'snippet': 'The use of biometrics has a unique impact upon refugees and asylum seekers, and it has the potential to improve national and.',
   'date': 'Apr 7, 2013',
   'position': 5},
  {'title': '[PDF] Biometric Specifications for Personal Identity Verification',
   'link': 'https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-76-2.pdf',
   'snippet': 'For planning and transition purposes, Federal agencies may wish to closely follow the development of these new publications by NIST. Organizations are ...',
   'date': 'Jul 11, 2013',
   'attributes': {'Missing': 'announced everyone?'},
   'position': 6},
  {'title': 'ID2020 | GHPC | Digital Identity Alliance',
   'link': 'https://id2020.org/',
   'snippet': 'ID2020 and the Digital Impact Alliance announced plans to unite in the push for digital transformation efforts to serve the best interests and wellbeing of ...',
   'date': 'Aug 16, 2016',
   'position': 7},
  {'title': 'Digital ID in Africa this week: International Identity Day, biometric ...',
   'link': 'https://www.biometricupdate.com/201909/digital-id-in-africa-this-week-international-identity-day-biometric-electoral-rolls-on-display-in-ghana',
   'snippet': 'The exercise in Nigeria aims to register biographic and biometric details of all foreign nationals over age 18 who have been in the country for over 90 ...',
   'date': 'Sep 13, 2019',
   'attributes': {'Missing': 'everyone?'},
   'position': 8},
  {'title': 'The Future Is Biometric - Oliver Wyman',
   'link': 'https://www.oliverwyman.com/our-expertise/insights/2019/oct/oliver-wyman-transport-and-logistics-2019/21st-century-travel/the-future-is-biometric.html',
   'snippet': 'The goal would be for travelers to use biometrics to replace the need for air or rail tickets or an official ID to check into a hotel, rent a car, or board a ...',
   'date': 'Oct 7, 2019',
   'attributes': {'Missing': 'everyone?'},
   'position': 9},
  {'title': '[PDF] DHS/NPPD-002 Automated Biometric Identification System (IDENT)',
   'link': 'https://www.dhs.gov/sites/default/files/publications/privacy-pia-nppd-ident-december2012.pdf',
   'snippet': 'The Automated Biometric Identification System (IDENT) is the central DHS-wide system for storage and processing of biometric and associated biographic ...',
   'date': 'Dec 7, 2012',
   'attributes': {'Missing': 'announced everyone?'},
   'position': 10}],
 'What is the purpose of the biometric ID system mentioned in the claim?\n': [{'title': 'What is Biometrics? How is it used in security? - Kaspersky',
   'link': 'https://usa.kaspersky.com/resource-center/definitions/biometrics?srsltid=AfmBOorKZy0bAYoPCO3CCZldZGQkwFqLOvCIPzWdVIzTsL0uRfuDOhWH',
   'snippet': "Each person's unique biometric identity can be used to replace or at least augment password systems for computers, phones, and restricted access rooms and ...",
   'date': 'Apr 24, 2018',
   'position': 1},
  {'title': 'Biometrics and Privacy – Issues and Challenges',
   'link': 'https://ovic.vic.gov.au/privacy/resources-for-organisations/biometrics-and-privacy-issues-and-challenges/',
   'snippet': "Biometrics are commonly used to authenticate a person's identity. Some examples of this include fingerprint or facial recognition to access smart phones, or the ...",
   'date': 'Jul 18, 2019',
   'position': 2},
  {'title': 'Biometrics - International Organization for Migration',
   'link': 'https://www.iom.int/biometrics',
   'snippet': 'The use of biometrics in registration processes can help to collect data to identify vulnerable individuals who may require additional assistance. Biometrics ...',
   'date': 'Mar 28, 2019',
   'position': 3},
  {'title': '[PDF] Justice Agency Use of Biometrics',
   'link': 'https://bja.ojp.gov/sites/g/files/xyckuh186/files/media/document/biometrics_flyer_v2.pdf',
   'snippet': "Biometric technology is commonly used in the justice system for: Verification • -confirmation of a person's identity (are they who they say they are?).",
   'date': 'Nov 10, 2010',
   'position': 4},
  {'title': 'Explainer: What is Biometric Identification?',
   'link': 'https://www.biometricupdate.com/201212/explainer-what-is-biometric-identification',
   'snippet': 'Biometric technologies use physical characteristics, such as voice tone or hand shape, to identify people automatically.',
   'date': 'Dec 6, 2012',
   'position': 5},
  {'title': 'What is Biometrics? - UpGuard',
   'link': 'https://www.upguard.com/blog/biometrics',
   'snippet': 'Biometrics is the technical term for body measurements and calculations, and human characteristics. Biometric authentication if a form of identification and ...',
   'date': 'Oct 30, 2019',
   'position': 6},
  {'title': 'Data at Your Fingertips Biometrics and the Challenges to Privacy',
   'link': 'https://www.priv.gc.ca/en/privacy-topics/health-genetic-and-other-body-information/gd_bio_201102/',
   'snippet': 'Biometric systems record personal information about identifiable individuals. That means their use by the federal government falls under the provisions of the ...',
   'date': 'Feb 16, 2011',
   'position': 7},
  {'title': '[PDF] Biometric Specifications for Personal Identity Verification',
   'link': 'https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-76-2.pdf',
   'snippet': 'For the preparation of biometric data suitable for the Federal Bureau of Investigation (FBI) background check, SP 800-76 references the ANSI/NIST Fingerprint ...',
   'date': 'Jul 11, 2013',
   'position': 8},
  {'title': 'Biometric authentication - Scholarpedia',
   'link': 'http://www.scholarpedia.org/article/Biometric_authentication',
   'snippet': 'Biometric recognition (also known as biometrics) refers to the automated recognition of individuals based on their biological and behavioral traits.',
   'date': 'Oct 21, 2011',
   'position': 9}],
 'Are there any existing UN programs that use biometric identification technologies?\n': [{'title': '[PDF] compendium-biometrics-20180618-en.pdf - the United Nations',
   'link': 'https://www.un.org/counterterrorism/sites/www.un.org.counterterrorism/files/compendium-biometrics-20180618-en.pdf',
   'snippet': 'NB This Compendium deals mainly with those physical biometrics that are associated with human identity (face, fingerprints, DNA etc.) and not behaviour.',
   'date': 'Jun 18, 2018',
   'attributes': {'Missing': 'existing programs'},
   'position': 1},
  {'title': 'United Nations High Commissioner for Refugees and Accenture ...',
   'link': 'https://newsroom.accenture.com/news/2015/united-nations-high-commissioner-for-refugees-and-accenture-deliver-global-biometric-identity-management-system-to-aid-displaced-persons',
   'snippet': '“The Biometric Identity Management System uses advanced technology to secure and preserve the identity of refugees from the time they register with UNHCR until ...',
   'date': 'May 19, 2015',
   'position': 2},
  {'title': 'UNCTED & BIOMETRICS INSTITUTE JOINT PROJECT ON ...',
   'link': 'https://www.biometricsinstitute.org/uncted-biometrics-institute-joint-project-on-biometrics-and-counter-terrorism/',
   'snippet': 'This project works on a Compendium of good and recommended Practices on the Responsible Use and Sharing of Biometrics in Identifying Terrorists.',
   'date': 'Feb 6, 2018',
   'attributes': {'Missing': 'programs | Show results with:programs'},
   'position': 3},
  {'title': '[PDF] IOM AND BIOMETRICS - International Organization for Migration',
   'link': 'https://www.iom.int/sites/default/files/our_work/DMM/IBM/iom_and_biometrics_external_info_sheet_november_2018.pdf',
   'snippet': 'With the help of biometric technologies for identity management, IOM is now better placed to support governments, partner organizations and migrants. The.',
   'date': 'Nov 15, 2018',
   'attributes': {'Missing': 'existing | Show results with:existing'},
   'position': 4},
  {'title': '[PDF] United Nations High Commissioner for Refugees (UNHCR ...',
   'link': 'https://www.dhs.gov/sites/default/files/publications/privacy-pia-uscis081-unhcr-august2019.pdf',
   'snippet': 'The biometrics from UNHCR are used to help establish an initial identity that allows USCIS to later biometrically verify that the individual being processed by ...',
   'date': 'Aug 13, 2019',
   'position': 5},
  {'title': '[PDF] Biometrics in the Humanitarian Sector - The Engine Room',
   'link': 'https://www.theengineroom.org/wp-content/uploads/2018/03/Engine-Room-Oxfam-Biometrics-Review.pdf',
   'snippet': 'Widespread deployment of biometrics in development and humanitarian contexts: In 2015, UNHCR began rolling out its global Biometric Identity Management System ...',
   'date': 'Mar 27, 2018',
   'position': 6},
  {'title': 'Biometric Standards Program and Resource Center | NIST',
   'link': 'https://www.nist.gov/programs-projects/biometric-standards-program-and-resource-center',
   'snippet': 'Summary: Supporting the national strategy on biometrics and the development of required biometric standards is the cornerstone of our program.',
   'date': 'Jan 8, 2010',
   'attributes': {'Missing': 'existing | Show results with:existing'},
   'position': 7},
  {'title': 'Registration and identity management - UNHCR',
   'link': 'https://www.unhcr.org/us/what-we-do/protect-human-rights/protection/registration-and-identity-management',
   'snippet': 'PRIMES is comprised of several repositories for personal data (biographic and biometric) and supporting information, along with multiple tools which safely make ...',
   'date': 'May 17, 2016',
   'attributes': {'Missing': 'existing | Show results with:existing'},
   'position': 8},
  {'title': 'DHS/USCIS/PIA-081 United Nations High Commissioner for ...',
   'link': 'https://www.dhs.gov/publication/dhsuscispia-081-united-nations-high-commissioner-refugees-unhcr-information-data-share',
   'snippet': 'UNHCR is now directly sharing biometric and associated biographic information with DHS Office of Biometric Identity Management (OBIM) Automated Biometric ...',
   'date': 'Aug 15, 2019',
   'position': 9}],
 'What are the potential benefits and risks associated with a global biometric ID system?\n': [{'title': 'Biometrics and Privacy – Issues and Challenges',
   'link': 'https://ovic.vic.gov.au/privacy/resources-for-organisations/biometrics-and-privacy-issues-and-challenges/',
   'snippet': 'This resource provides a high-level overview of what biometrics are, their benefits and uses in the public sector, and the information privacy implications ...',
   'date': 'Jul 18, 2019',
   'position': 1},
  {'title': 'Using biometrics - NCSC.GOV.UK',
   'link': 'https://www.ncsc.gov.uk/collection/device-security-guidance/policies-and-settings/using-biometrics',
   'snippet': 'This guidance will help organisations assess the benefits of using biometrics on devices against potential security risks.',
   'date': 'Jan 23, 2020',
   'attributes': {'Missing': 'global | Show results with:global'},
   'position': 2},
  {'title': 'Advantages and uses of biometrics - Iberdrola',
   'link': 'https://www.iberdrola.com/innovation/advantages-and-uses-of-biometrics',
   'snippet': 'The definition of biometric identification says that it is a method for recognising people based on their physiological or behavioural traits.',
   'date': 'Jul 12, 2018',
   'position': 3},
  {'title': '[PDF] Justice Agency Use of Biometrics',
   'link': 'https://bja.ojp.gov/sites/g/files/xyckuh186/files/media/document/biometrics_flyer_v2.pdf',
   'snippet': 'Biometric tools can be used for identification ... The following examples illustrate both the benefits and problems that can arise from the use of biometric ...',
   'date': 'Nov 10, 2010',
   'position': 4},
  {'title': 'Understanding Identity Systems Part 3: The Risks of ID',
   'link': 'http://privacyinternational.org/explainer/2672/understanding-identity-systems-part-3-risks-id',
   'snippet': 'This can be a result of issues like the fading of fingerprints (the elderly and manual workers being particularly at risk) or cataracts affecting iris scans.',
   'date': 'Jan 31, 2019',
   'position': 5},
  {'title': 'The Potential Drawbacks to Digital Identification',
   'link': 'https://workingcapitalreview.com/2021/04/the-potential-drawbacks-to-digital-identification/',
   'snippet': "First, it's seen as a potentially more secure method than, say, passwords or Social Security numbers, which are both hacked relatively easily. Second, ...",
   'date': 'Nov 13, 2018',
   'attributes': {'Missing': 'benefits | Show results with:benefits'},
   'position': 6},
  {'title': 'Biometric refugee registration: between benefits, risks and ethics',
   'link': 'https://blogs.lse.ac.uk/internationaldevelopment/2019/07/18/biometric-refugee-registration-between-benefits-risks-and-ethics/',
   'snippet': "By uniquely identifying individuals, biometric registration can reduce the risk of miscounting and subsequently reduce the risk of fraud and 'aid wastage'.",
   'date': 'Jul 18, 2019',
   'position': 7},
  {'title': 'The benefits and risks of national identification programmes',
   'link': 'https://www.emeraldgrouppublishing.com/archived/learning/management_thinking/articles/national_id.htm',
   'snippet': 'Furthermore, many believe that implementing a NICP could deter terrorism and other related societal crimes through proper pre-screening and tracking ...',
   'date': 'Sep 5, 2008',
   'position': 8},
  {'title': 'Benefits, concerns around national identification systems | News',
   'link': 'https://www.hsph.harvard.edu/news/features/benefits-concerns-around-national-identification-systems/',
   'snippet': 'In addition to helping people access services, ID cards can also foster a sense of social inclusion, said panelists during a session on uses of local and ...',
   'date': 'Nov 24, 2015',
   'position': 9},
  {'title': '[PDF] Biometrics in the Humanitarian Sector - The Engine Room',
   'link': 'https://www.theengineroom.org/wp-content/uploads/2018/03/Engine-Room-Oxfam-Biometrics-Review.pdf',
   'snippet': 'The introduction of biometrics into registration and identification has the potential to streamline beneficiary registration and speed up the delivery of ...',
   'date': 'Mar 27, 2018',
   'position': 10}],
 'How would the implementation of a biometric ID system by the UN be funded and managed?\n': [{'title': 'UNHCR – Guidance on Registration and Identity Management',
   'link': 'https://www.unhcr.org/registration-guidance/chapter3/registration-tools/',
   'snippet': "BIMS is UNHCR's principle biometric identity management system. First rolled out in 2015, BIMS has a centralized database allowing real-time consolidation and ...",
   'date': 'Aug 28, 2018',
   'attributes': {'Missing': 'UN | Show results with:UN'},
   'position': 1},
  {'title': '[PDF] Biometrics in the Humanitarian Sector - The Engine Room',
   'link': 'https://www.theengineroom.org/wp-content/uploads/2018/03/Engine-Room-Oxfam-Biometrics-Review.pdf',
   'snippet': 'UNHCR and WFP now operate wide-ranging biometrics registration systems, to which implementing partners also have access and contribute, broadening programmatic ...',
   'date': 'Mar 27, 2018',
   'position': 2},
  {'title': '[PDF] IOM AND BIOMETRICS - International Organization for Migration',
   'link': 'https://www.iom.int/sites/default/files/our_work/DMM/IBM/iom_and_biometrics_external_info_sheet_november_2018.pdf',
   'snippet': 'With the help of biometric technologies for identity management, IOM is now better placed to support governments, partner organizations and migrants. The.',
   'date': 'Nov 15, 2018',
   'position': 3},
  {'title': '[PDF] Digital Financial Inclusion',
   'link': 'https://www.un.org/esa/ffd/wp-content/uploads/2016/01/Digital-Financial-Inclusion_ITU_IATF-Issue-Brief.pdf',
   'snippet': 'FG DFS is developing a set of operational recommendations, tools and solutions that will fast track policy reform to support numerous developing countries in ...',
   'date': 'Jul 14, 2016',
   'position': 4},
  {'title': '[PDF] ID4D – IDENTIFICATION FOR DEVELOPMENT - World Bank',
   'link': 'https://pubdocs.worldbank.org/en/325451527084344478/ID4D-ProgramFlyer-V52018.pdf',
   'snippet': 'The World Bank Group (WBG) helps countries build more robust and inclusive identification systems through analytics, assessments, and financing. Digital ...',
   'date': 'Feb 15, 2017',
   'position': 5},
  {'title': 'Using Biometrics to Keep Citizens Safe | OSCE',
   'link': 'https://www.osce.org/magazine/416453',
   'snippet': 'UNSCR 2396 requires UN Member States to develop and implement systems to collect biometric data in compliance with domestic law and international human rights ...',
   'date': 'Apr 5, 2019',
   'position': 6},
  {'title': '[PDF] Faces, Fingerprints & Feet | UNICEF Data',
   'link': 'https://data.unicef.org/wp-content/uploads/2019/10/Biometrics_guidance_document_faces_fingersprint_feet-July-2019.pdf',
   'snippet': 'UNHCR and the WFP, for example, have fully integrated biometrics into their cash management programs (7), and more countries are investing in biometric ...',
   'date': 'Jul 15, 2019',
   'attributes': {'Missing': 'funded | Show results with:funded'},
   'position': 7},
  {'title': 'Digital ID systems: the global #WhyID campaign - Access Now',
   'link': 'https://www.accessnow.org/campaign/whyid/',
   'snippet': 'Led by Access Now, this campaign promote meaningful change in the implementation of digital ID systems around the world.',
   'date': 'Oct 21, 2019',
   'position': 8},
  {'title': '[PDF] Briefing to the UN Counter-Terrorism Executive Directorate on the ...',
   'link': 'https://privacyinternational.org/sites/default/files/2019-07/PI%20briefing%20on%20biometrics%20final.pdf',
   'snippet': 'biometrics system is used to store and manage personal identification information that can be used “to support law enforcement, security, and intelligence ...',
   'date': 'Jun 15, 2019',
   'position': 9},

In [14]:
d5= d5.T
d5

,title,snippet,url,text
0,,"Since the FDA's approval, human microchip impl...",https://natlawreview.com/article/chipping-away...,
1,,Having discussed the components of RFID microc...,https://natlawreview.com/article/chipping-away...,
2,,Well-known examples include how to use data wh...,https://www3.weforum.org/docs/Unlocking_Techno...,
3,,data from health plans and claims as well as b...,https://www.broadbandcommission.org/wp-content...,
4,,"identification of people, chip implants for th...",https://www.rand.org/content/dam/rand/pubs/tec...,
...,...,...,...,...
1530,,This issue brief provides a snapshot of curren...,https://www.kff.org/medicaid/issue-brief/snaps...,Snapshots of Recent State Initiatives in Medic...
1531,,"Over the past year, California has passed seve...",https://www.pm360online.com/california-will-re...,Linkedin\nAs President Trump continues to make...
1532,,"For example, California, Connecticut, and Verm...",https://pmc.ncbi.nlm.nih.gov/articles/PMC6355356/,Copyright and License information\n1Department...
1533,,Comment: One commenter stated that Congress ha...,https://www.hhs.gov/sites/default/files/cms-41...,
1534,,High drug prices are straining state health bu...,https://law.yale.edu/sites/default/files/area/...,

In [20]:
d5.loc[1532, 'snippet']

'For example, California, Connecticut, and Vermont have passed legislation requiring companies to justify price increases beyond a certain threshold (82–84).'

In [1]:
import json
import pandas as pd

df= pd.read_json("./PoliResult/out/decompose/claim_150_keyword_extraction.json")
df

,id,label,claim,date,keywords
0,TUD98,FALSE,The United Nations plans to implant everyone w...,2020-02-20,"[United Nations, biometric ID, implant, Februa..."
1,TUD44,TRUE,The Machinists Union does not (support the USM...,2011-01-07,"[Machinists Union, USMCA trade deal, environme..."
2,TUD62,FALSE,Gov. Tony Evers proposed raising taxes on the ...,2020-01-22,"[Gov. Tony Evers , raising taxes , agricultu..."
3,TUD24,TRUE,"If you're a black woman, you're 320% more like...",2019-12-19,"[black women childbirth mortality, black women..."
4,TUD102,FALSE,Left-wing activist John Sullivan incited (the)...,2021-01-07,"[John Sullivan, left-wing activist, US Capitol..."
5,TUD37,TRUE,Mike Bloomberg is a candidate who in 2015 stat...,2020-02-15,"[Mike Bloomberg, minimum wage, 2015, Bernie Sa..."
6,TUD83,FALSE,The impeachment process against Donald Trump p...,2019-10-31,"[Donald Trump impeachment process, Donald Trum..."
7,TUD7,TRUE,You have literally 140 people dying every day ...,2019-11-25,"[opioid-related overdoses, 140 people dying ev..."
8,TUD113,FALSE,The CDC finally admits its COVID-19 test can’t...,2022-01-29,"[CDC, COVID-19 test, flu, difference, Instagra..."
9,TUD51,HALF TRUE,I have also overseen historic funding increase...,2020-02-04,"[historic funding increases, child care, 17 st..."
10,TUD40,HALF TRUE,Marijuana has a unique impact on the developin...,2019-08-30,"[Marijuana, impact, developing brain, brain ad..."

In [ ]:
import json
import pandas as pd

df= pd.read_json("./PoliResult/out/grounding/test/corpus_crawled_150.json")
df

/tmp/ipykernel_813731/3042972164.py:4: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df= pd.read_json("./PoliResult/out/grounding/test/final_serp_150_dict.jsonl")

ValueError: Expected object or value

In [38]:
with open(f"./PoliResult/out/grounding/final_serp_150_dict.jsonl") as fp:
    dataset = json.load(fp)

print(dataset[22])

{'id': 'TUD128', 'label': 'HALF TRUE', 'claim': 'Comprehensive immigration reform, the bill we had back in 2013 ... brought the debt down $158 billion.', 'date': 'February 18, 2019', 'keywords': ['Comprehensive immigration reform ', ' 2013 immigration bill ', ' $158 billion debt reduction ', ' economic impact of 2013 immigration bill ', ' Congressional Budget Office immigration reform 2013'], 'google_search': {'Comprehensive immigration reform , 2013 immigration bill , $158 billion debt reduction , economic impact of 2013 immigration bill , Congressional Budget Office immigration reform 2013': [{'title': 'Would 2013 immigration bill have saved $158 billion - PolitiFact', 'link': 'https://www.politifact.com/factchecks/2019/feb/20/amy-klobuchar/would-2013-immigration-bill-have-saved-158-b/', 'snippet': '"Comprehensive immigration reform, the bill we had back in 2013 ... brought the debt down $158 billion." true half-true. Immigration ...', 'date': 'Feb 20, 2019', 'position': 1}, {'title': 'The Economic Impact of S. 744, the Border Security, Economic ...', 'link': 'https://www.cbo.gov/publication/44346', 'snippet': 'S. 744 would boost economic output—CBO projects—by 3.3 percent in 2023 and by 5.4 percent in 2033. Employment, investment, and productivity ...', 'date': 'Jun 18, 2013', 'attributes': {'Missing': '$158 2019'}, 'position': 2}, {'title': '[PDF] S. 744 - Congressional Budget Office', 'link': 'https://www.cbo.gov/system/files/113th-congress-2013-2014/costestimate/s744_0.pdf', 'snippet': 'The bill also would directly appropriate funds for tightening border security and enforcing immigration laws, and would authorize additional ...', 'date': 'Jun 18, 2013', 'attributes': {'Missing': 'February | Show results with:February'}, 'position': 3}, {'title': 'A Guide to S.744: Understanding the 2013 Senate Immigration Bill', 'link': 'https://www.americanimmigrationcouncil.org/research/guide-s744-understanding-2013-senate-immigration-bill', 'snippet': 'This guide to provide policymakers, the media, and the public with an easy-to-understand guide to the main components of S. 744 and the purpose behind them.', 'date': 'Jul 10, 2013', 'attributes': {'Missing': 'debt 2019'}, 'position': 4}, {'title': 'S.744 - 113th Congress (2013-2014): Border Security, Economic ...', 'link': 'https://www.congress.gov/bill/113th-congress/senate-bill/744', 'snippet': "Amends the Illegal Immigration Reform and Immigrant Responsibility Act of 1996 to repeal the denial of an unlawful alien's eligibility for higher education ...", 'attributes': {'Missing': '$158 debt February'}, 'position': 5}, {'title': '[PDF] THE ECONOMIC BENEFITS OF FIXING OUR BROKEN ...', 'link': 'https://obamawhitehouse.archives.gov/sites/default/files/docs/report.pdf', 'snippet': 'According to CBO, commonsense immigration reform will lead to greater economic growth because it will add more high-demand workers to the labor force, increase ...', 'attributes': {'Missing': '2019 | Show results with:2019'}, 'position': 6}, {'title': 'Senate Report 113-40 - BORDER SECURITY, ECONOMIC ... - GovInfo', 'link': 'https://www.govinfo.gov/content/pkg/CRPT-113srpt40/html/CRPT-113srpt40.htm', 'snippet': 'Raul Hinojosa-Ojeda, The Economic Benefits of Comprehensive Immigration Reform ... Recent Border Security Legislation In the absence of comprehensive immigration ...', 'attributes': {'Missing': '$158 debt'}, 'position': 7}, {'title': "The Immigration Bill's '$6.3 Trillion Price Tag' - FactCheck.org", 'link': 'https://www.factcheck.org/2013/06/the-immigration-bills-6-3-trillion-price-tag-2/', 'snippet': 'On July 3, the CBO released a cost analysis of the legislation and concluded it would reduce the deficit by $158 billion over the next 10 years, ...', 'date': 'Jun 4, 2013', 'attributes': {'Missing': '18, 2019'}, 'position': 8}, {'title': 'CBO Report: Immigration Reform Will Shrink the Deficit and Grow ...', 'link': 'https://obamawhitehouse.archives.gov/blog/2013/06/18/cbo-report-immigration-reform-will-shrink-deficit-and-grow-economy', 'snippet': 'CBO estimates that fixing our broken immigration system will reduce federal deficits by about $200 billion over the next 10 years, and about ...', 'date': 'Jun 18, 2013', 'attributes': {'Missing': 'Comprehensive $158 debt 2019'}, 'position': 9}, {'title': 'CBO Estimates Immigration Bill Would Cut Deficit by $158 Billion', 'link': 'https://www.taxnotes.com/lr/resolve/tax-notes-today-federal/cbo-estimates-immigration-bill-would-cut-deficit-by-%24158-billion/f5kv', 'snippet': "As shown in the attached table, CBO and JCT estimate that the act's effects on those two programs would reduce budget deficits by $260 billion ...", 'date': 'Jul 25, 2013', 'attributes': {'Missing': 'Comprehensive reform , debt reform 18, 2019'}, 'position': 10}]}}

In [23]:
df.columns

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       668, 669, 670, 671, 672, 673, 674, 675, 676, 677],
      dtype='int64', length=678)

In [21]:
#qrels= pd.read_json("./PoliResult/out/grounding/test/qrels_crawled_150.json")
#qrels

with open('./PoliResult/out/grounding/test/qrels_crawled_150.json', 'r') as file:
    qrels = json.load(file)

print(qrels)

{'0': {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1}, '1': {'5': 1, '6': 1, '7': 1, '8': 1, '9': 1}, '2': {'10': 1, '11': 1}, '3': {'12': 1, '13': 1, '14': 1, '15': 1, '16': 1}, '4': {'17': 1, '18': 1}, '5': {'19': 1, '20': 1, '21': 1, '22': 1, '23': 1}, '6': {'24': 1, '25': 1, '26': 1, '27': 1, '28': 1}, '7': {'29': 1, '30': 1, '31': 1, '32': 1, '33': 1}, '8': {'34': 1, '35': 1, '36': 1, '37': 1, '38': 1}, '9': {'39': 1, '40': 1, '41': 1, '42': 1, '43': 1}, '10': {'44': 1, '45': 1, '46': 1, '47': 1, '48': 1}, '11': {'49': 1, '50': 1, '51': 1, '52': 1, '53': 1}, '12': {'54': 1, '55': 1, '56': 1, '57': 1, '58': 1}, '13': {'59': 1, '60': 1, '61': 1, '62': 1, '63': 1}, '14': {'64': 1, '65': 1, '66': 1, '67': 1}, '15': {'68': 1, '69': 1, '70': 1, '71': 1, '72': 1}, '16': {'73': 1, '74': 1, '75': 1, '76': 1, '77': 1}, '17': {'78': 1, '79': 1, '80': 1, '81': 1, '82': 1}, '18': {'83': 1, '84': 1, '85': 1, '86': 1, '87': 1}, '19': {'88': 1, '89': 1, '90': 1, '91': 1, '92': 1}, '20': {'93': 1, '94': 1, '95': 1, '96': 1, '97': 1}, '21': {'98': 1, '99': 1, '100': 1, '101': 1, '102': 1}, '22': {'103': 1, '104': 1, '105': 1, '106': 1, '107': 1}, '23': {'108': 1, '109': 1, '110': 1, '111': 1, '112': 1}, '24': {'113': 1, '114': 1, '115': 1, '116': 1, '117': 1}, '25': {'118': 1, '119': 1, '120': 1}, '26': {'121': 1, '122': 1, '123': 1, '124': 1, '125': 1}, '27': {'126': 1, '127': 1, '128': 1, '129': 1}, '28': {'130': 1, '131': 1, '132': 1}, '29': {'133': 1, '134': 1, '135': 1}, '30': {'136': 1, '137': 1, '138': 1, '139': 1, '140': 1}, '31': {'141': 1, '142': 1, '143': 1, '144': 1, '145': 1}, '32': {'146': 1, '147': 1, '148': 1, '149': 1, '150': 1}, '33': {'151': 1, '152': 1, '153': 1, '154': 1, '155': 1}, '34': {'156': 1, '157': 1, '158': 1, '159': 1, '160': 1}, '35': {'161': 1, '162': 1}, '36': {'163': 1, '164': 1, '165': 1}, '37': {'166': 1, '167': 1, '168': 1, '169': 1, '170': 1}, '38': {'171': 1, '172': 1, '173': 1, '174': 1, '175': 1}, '39': {'176': 1, '177': 1, '178': 1}, '40': {'179': 1, '180': 1, '181': 1, '182': 1, '183': 1}, '41': {'184': 1, '185': 1, '186': 1, '187': 1, '188': 1}, '42': {'189': 1, '190': 1, '191': 1, '192': 1, '193': 1}, '43': {'194': 1, '195': 1, '196': 1, '197': 1, '198': 1}, '44': {'199': 1, '200': 1, '201': 1, '202': 1, '203': 1}, '45': {'204': 1, '205': 1, '206': 1, '207': 1, '208': 1}, '46': {'209': 1, '210': 1, '211': 1}, '47': {'212': 1, '213': 1, '214': 1, '215': 1}, '48': {'216': 1}, '49': {'217': 1, '218': 1, '219': 1, '220': 1, '221': 1}, '50': {'222': 1, '223': 1, '224': 1, '225': 1, '226': 1}, '51': {'227': 1, '228': 1, '229': 1, '230': 1, '231': 1}, '52': {'232': 1, '233': 1, '234': 1}, '53': {'235': 1, '236': 1, '237': 1, '238': 1, '239': 1}, '54': {'240': 1, '241': 1, '242': 1, '243': 1, '244': 1}, '55': {'245': 1, '246': 1}, '56': {'247': 1, '248': 1, '249': 1, '250': 1, '251': 1}, '57': {'252': 1, '253': 1, '254': 1, '255': 1, '256': 1}, '58': {'257': 1, '258': 1, '259': 1, '260': 1, '261': 1}, '59': {'262': 1}, '60': {'263': 1, '264': 1, '265': 1, '266': 1, '267': 1}, '61': {'268': 1, '269': 1, '270': 1, '271': 1, '272': 1}, '62': {'273': 1, '274': 1, '275': 1, '276': 1, '277': 1}, '63': {}, '64': {'278': 1, '279': 1, '280': 1, '281': 1, '282': 1}, '65': {'283': 1, '284': 1, '285': 1, '286': 1, '287': 1}, '66': {'288': 1, '289': 1}, '67': {'290': 1, '291': 1, '292': 1, '293': 1}, '68': {'294': 1, '295': 1, '296': 1, '297': 1, '298': 1}, '69': {'299': 1, '300': 1, '301': 1, '302': 1, '303': 1}, '70': {'304': 1, '305': 1, '306': 1, '307': 1, '308': 1}, '71': {'309': 1, '310': 1, '311': 1, '312': 1, '313': 1}, '72': {'314': 1, '315': 1, '316': 1, '317': 1, '318': 1}, '73': {'319': 1, '320': 1, '321': 1, '322': 1}, '74': {'323': 1, '324': 1, '325': 1, '326': 1, '327': 1}, '75': {'328': 1, '329': 1, '330': 1, '331': 1}, '76': {'332': 1, '333': 1, '334': 1, '335': 1, '336': 1}, '77': {'337': 1, '338': 1, '339': 1, '340': 1, '341': 1}, '78': {'342': 1, '343': 1, '344': 1, '345': 1, '346': 1}, '79': {'347': 1, '348': 1, '349': 1, '350': 1}, '80': {'351': 1, '352': 1, '353': 1, '354': 1, '355': 1}, '81': {'356': 1, '357': 1, '358': 1, '359': 1, '360': 1}, '82': {'361': 1, '362': 1, '363': 1, '364': 1, '365': 1}, '83': {'366': 1, '367': 1, '368': 1, '369': 1, '370': 1}, '84': {'371': 1, '372': 1, '373': 1, '374': 1, '375': 1}, '85': {'376': 1, '377': 1, '378': 1, '379': 1, '380': 1}, '86': {'381': 1, '382': 1, '383': 1, '384': 1, '385': 1}, '87': {'386': 1, '387': 1, '388': 1}, '88': {'389': 1, '390': 1, '391': 1, '392': 1, '393': 1}, '89': {'394': 1, '395': 1, '396': 1, '397': 1}, '90': {'398': 1, '399': 1, '400': 1, '401': 1, '402': 1}, '91': {'403': 1, '404': 1, '405': 1, '406': 1, '407': 1}, '92': {'408': 1, '409': 1, '410': 1, '411': 1, '412': 1}, '93': {'413': 1, '414': 1, '415': 1, '416': 1, '417': 1}, '94': {'418': 1, '419': 1, '420': 1, '421': 1, '422': 1}, '95': {'423': 1, '424': 1, '425': 1, '426': 1, '427': 1}, '96': {'428': 1, '429': 1, '430': 1, '431': 1, '432': 1}, '97': {'433': 1, '434': 1, '435': 1, '436': 1, '437': 1}, '98': {'438': 1, '439': 1, '440': 1, '441': 1, '442': 1}, '99': {'443': 1, '444': 1, '445': 1, '446': 1, '447': 1}, '100': {'448': 1, '449': 1, '450': 1, '451': 1, '452': 1}, '101': {'453': 1, '454': 1, '455': 1, '456': 1, '457': 1}, '102': {'458': 1, '459': 1, '460': 1, '461': 1, '462': 1}, '103': {'463': 1, '464': 1, '465': 1, '466': 1, '467': 1}, '104': {'468': 1, '469': 1, '470': 1, '471': 1, '472': 1}, '105': {'473': 1, '474': 1, '475': 1, '476': 1}, '106': {'477': 1, '478': 1, '479': 1, '480': 1, '481': 1}, '107': {'482': 1, '483': 1, '484': 1, '485': 1, '486': 1}, '108': {'487': 1, '488': 1, '489': 1, '490': 1, '491': 1}, '109': {'492': 1}, '110': {'493': 1, '494': 1, '495': 1, '496': 1, '497': 1}, '111': {'498': 1, '499': 1, '500': 1, '501': 1, '502': 1}, '112': {'503': 1, '504': 1}, '113': {'505': 1, '506': 1, '507': 1, '508': 1, '509': 1}, '114': {'510': 1, '511': 1, '512': 1, '513': 1, '514': 1}, '115': {'515': 1, '516': 1, '517': 1, '518': 1, '519': 1}, '116': {'520': 1, '521': 1, '522': 1, '523': 1, '524': 1}, '117': {'525': 1, '526': 1, '527': 1}, '118': {'528': 1, '529': 1, '530': 1, '531': 1, '532': 1}, '119': {'533': 1, '534': 1, '535': 1, '536': 1, '537': 1}, '120': {'538': 1, '539': 1, '540': 1, '541': 1, '542': 1}, '121': {'543': 1, '544': 1}, '122': {'545': 1, '546': 1, '547': 1, '548': 1, '549': 1}, '123': {'550': 1, '551': 1, '552': 1, '553': 1, '554': 1}, '124': {'555': 1, '556': 1, '557': 1}, '125': {'558': 1, '559': 1, '560': 1}, '126': {'561': 1, '562': 1, '563': 1, '564': 1, '565': 1}, '127': {'566': 1, '567': 1, '568': 1, '569': 1, '570': 1}, '128': {'571': 1, '572': 1, '573': 1, '574': 1, '575': 1}, '129': {'576': 1, '577': 1, '578': 1, '579': 1, '580': 1}, '130': {'581': 1, '582': 1, '583': 1, '584': 1}, '131': {'585': 1, '586': 1, '587': 1, '588': 1}, '132': {'589': 1, '590': 1, '591': 1, '592': 1, '593': 1}, '133': {'594': 1, '595': 1, '596': 1, '597': 1, '598': 1}, '134': {'599': 1, '600': 1, '601': 1, '602': 1, '603': 1}, '135': {'604': 1, '605': 1, '606': 1, '607': 1, '608': 1}, '136': {'609': 1, '610': 1, '611': 1, '612': 1, '613': 1}, '137': {'614': 1, '615': 1, '616': 1, '617': 1, '618': 1}, '138': {'619': 1, '620': 1, '621': 1, '622': 1, '623': 1}, '139': {'624': 1, '625': 1, '626': 1, '627': 1, '628': 1}, '140': {'629': 1, '630': 1, '631': 1, '632': 1, '633': 1}, '141': {'634': 1, '635': 1, '636': 1, '637': 1}, '142': {'638': 1, '639': 1, '640': 1, '641': 1, '642': 1}, '143': {'643': 1, '644': 1, '645': 1, '646': 1, '647': 1}, '144': {'648': 1, '649': 1, '650': 1, '651': 1, '652': 1}, '145': {'653': 1, '654': 1, '655': 1, '656': 1, '657': 1}, '146': {'658': 1, '659': 1, '660': 1, '661': 1, '662': 1}, '147': {'663': 1, '664': 1, '665': 1, '666': 1, '667': 1}, '148': {'668': 1, '669': 1, '670': 1, '671': 1, '672': 1}, '149': {'673': 1, '674': 1, '675': 1, '676': 1, '677': 1}}

In [18]:
l= list(data['0'].keys())
l

['0', '1', '2', '3', '4']

In [25]:
out=[]
for i in range(150):
    ev_col= list(qrels[str(i)])
    ev= ''
    for j in ev_col:
        ev+= df.loc['text', int(j)]

    out.append({'row': i, 'evidence': ev})


with open(f"./PoliResult/out/grounding/scraped_150_full_text.json","w",) as f:
    json.dump(out, f)

In [39]:
with open(f"./PoliResult/out/grounding/scraped_150_full_text.json") as fp:
            evidence_df= pd.read_json(fp)

evidence_df

     row                                           evidence
0      0  United Nations Legal Identity Agenda\nBackgrou...
1      1  iMail\nDecember 10, 2019\nWASHINGTON, Dec. 10,...
2      2  Press Release: Gov. Evers, DATCP Announce Wisc...
3      3  Working Together to Reduce Black Maternal Mort...
4      4  From Wikipedia, the free encyclopedia\nAmerica...
..   ...                                                ...
145  145  About NW MIRECC VA and NW MIRECC History Execu...
146  146  Journal of Clinical and Translational Research...
147  147  Menu\nCiting this information:\nNOAA National ...
148  148  Alcohol Use Disorder (AUD) in the United State...
149  149  Opioids\nBack to top\nOn 100th Full Day in Off...

[150 rows x 2 columns]

In [43]:
evidence_df.to_csv("150_full_evidence.csv")

In [42]:
evidence_df.loc[21, 'evidence']

'See All\nOverview\nNew York State Laws are designed to remove firearms from those who seek to do harm to themselves or others. This means keeping the minority of individuals with serious mental illness who may be dangerous away from access to firearms. These laws should not dissuade any individual from seeking mental health services they need.\nSection 9.46 of the Mental Hygiene Law (MHL) requires that mental health professionals who are currently providing treatment services to an individual make a report, if they conclude, using reasonable professional judgment, that the individual is likely to engage in conduct that would result in serious harm to self or others.\nThe “Red Flag” Law, also known as the extreme risk protection order (ERPO) law, prevents individuals who show signs of being a threat to themselves or others from purchasing or possessing any kind of gun. It also requires such individuals to surrender any guns they own or possess.\nAn ERPO can be sought by multiple people in a person’s life including:\nA health or mental health care practitioner who examined the individual within the last six months;\nA member of the individual’s household;\nA school official;\nA police officer; or\nA district attorney.\nIf you are a mental health professional seeking more detailed instructions on how to file an ERPO, please visit the Office of Court Administration webpage . You can also visit the New York State Red Flag Law webpage for more information.\nFrequently Asked Questions\nWhen did the reporting requirement under Mental Hygiene Law (MHL) 9.46 become effective?\nThe reporting requirement became effective on March 16, 2013, and additional mental health professionals were included as reporters on July 6, 2022.\nWhat does the new MHL 9.46 require be reported?\nMHL 9.46 requires mental health professionals to report to their local director of community services (“DCS”) or his/her designees when, in their reasonable professional judgment, one of their patients is “likely to engage in conduct that would result in serious harm to self or others.”\nWho is required to report under MHL 9.46?\nThe reporting requirement extends to “mental health professionals,” defined in the law as the following professions – physicians, psychiatrists, psychologists, registered nurses, licensed clinical social workers, licensed master social worker, licensed mental health counselor, clinical nurse specialist, certified nurse practitioner, licensed clinical marriage and family therapist, or a licensed professional nurse.\nWho is potentially a subject of an MHL 9.46 report?\nAll persons receiving mental health treatment services from any of the types of mental health professionals identified in the law, regardless of the setting in which they work, may be subjects of 9.46 reports.\nDoes the reporting requirement apply to mental health professionals working in private practice, on general hospital wards, or other locations outside of psychiatric wards?\nYes, the requirement to report is not dependent upon the location of the treating professional or the patient.\nAre there exceptions to this reporting requirement?\nYes. A report is not required when, in the mental health professional’s reasonable professional judgment, a report would endanger him or her or would increase the danger to the potential victim or victims.\nWhat if there are several mental health professionals treating a particular individual – are all of them required to make a report?\nReports under MHL 9.46 are made using a clinician’s reasonable professional judgment. Different clinicians treating the same individual may not agree, which should not prevent any one, or all, of them from making a report.\nWhat information about the patient should be reported by mental health professionals?\nMental health professionals should convey information necessary to allow the DCS to review the matter and determine if a report to the NYS Division of Criminal Justice Services (DCJS) is required (e.g., what clinical evidence, history, and risk factors have caused the mental health professional to conclude that the patient is likely to engage in conduct that would result in serious harm to self or others).\nAre such reports in compliance with HIPAA?\nUnder HIPAA, because these informational disclosures are required by law, they can be made without the patient’s consent. HIPAA permits disclosures of protected health information without the authorization or consent of the individual to the extent that such disclosure is required by law and the disclosure complies with the requirements of that law.\nWhen should a mental health professional make a report?\nThe mental health professional should make a report as soon as possible.\nWhat information will a local DCS report to DCJS, and what can DCJS do with such information?\nA local DCS may only disclose a patient’s name and other non-clinical identifying information (e.g., date of birth, race, sex, SSN, address) to DCJS, and that information can be used by DJCS to determine if the patient has a firearms license.\nIf the patient has a firearms license, State Police will report that information to the local firearms licensing official, who must either suspend or revoke the license. The information may also be used in connection with a determination of firearms license eligibility should the subject of the report apply for a firearms license in the subsequent five years.\nHow long will DCJS retain the personal information they receive?\nDCJS must destroy information received five years after receipt.\nMental health professionals must make reports when, in their professional judgment, it is believed that the patient is “likely to engage in conduct that could seriously harm the patient him/herself or others.” What does that mean?\nThe standard “likelihood to result in serious harm” means threats of, or attempts at, suicide/serious bodily harm to self, or homicidal/violent behavior towards others. This standard justifies the need for immediate action, as a public safety measure, to prevent harm. Mental health professionals must use reasonable professional judgment when making this determination.\nIn general, a MHL 9.46 report would originate if the clinician determines the person is likely to engage in conduct that could seriously harm the patient and/or others (which could thus also trigger a MHL 9.46 emergency assessment). It is not, however, necessary to establish that the patient has a gun before making the report.\nCan mental health professionals who make a determination to report or not to report be held liable?\nThe law specifically provides that if a mental health professional uses “reasonable professional judgment” and “good faith” when making a determination, this decision cannot be the basis for any civil or criminal liability on the part of that professional.\n*Please note: This website is informational only and does not constitute legal advice.\nLearn More\nThe Effects of Prohibitions Associated with Mental Illness\nPrint-friendly summary\nReferences\nFederal law prohibits the possession or purchase of firearms by certain individuals who have been adjudicated as mentally ill or involuntarily committed to a mental institution. As of January 1, 2024, 35 states and the District of Columbia have laws restricting access to firearms by individuals with specific histories of mental illness. Although the laws in many states mirror the same restrictions found in federal law, some states have expanded the prohibitions to apply to a broader population, for example to individuals who have been voluntarily admitted into psychiatric hospitals or who have been ordered to attend outpatient treatment.\nSummary of Evidence for How Prohibitions Associated with Mental Illness Affect Outcomes\nWe systematically reviewed scientific evidence on broad classes of gun policies to understand how these policies affect different outcomes in the United States.\nEvidence Strength for Prohibitions Associated with Mental Illness\nEvidence is categorized as inconclusive, limited, moderate, or supportive. For some outcomes, not enough research met our inclusion criteria to assess the strength of evidence for the effects of prohibitions associated with mental illness. An absence of evidence does not mean that such prohibitions have no effect on those outcomes.\nDefensive Gun Use\nNo studies met our criteria.\nNo studies met our criteria.\nNo studies met our criteria.\nNo studies met our criteria.\nNo studies met our criteria.\nThere is inconclusive evidence for the effects of prohibitions associated with mental illness on suicide.\nNo studies met our criteria.\nThere is limited evidence that prohibitions associated with mental illness decrease violent crime.\nOutcomes\nNo studies met our criteria.\nGun Industry Outcomes\nNo studies met our criteria.\nHunting and Recreation\nNo studies met our criteria.\nMass Shootings\nNo studies met our criteria.\nPolice Shootings\nNo studies met our criteria.\nSuicide\nThere is inconclusive evidence for how prohibitions associated with mental illness affect suicide.\nUnintentional Injuries and Deaths\nNo studies met our criteria.\nViolent Crime\nThere is limited evidence that prohibitions associated with mental illness decrease violent crime.\nEvidence of Effects Among Studies That Met Our Inclusion Criteria\nViolent Crime\nFour studies evaluated the relationship of mental health–related prohibitions and violent crime. These studies did not examine laws establishing prohibiting conditions based on documented history of mental illness, but instead evaluated policies related to the reporting or assessment of mental health records as part of the background check process. All studies found that such checks were associated with reductions in violent crime, hospitalization, or homicides, although the methodological quality of these studies was uneven.\nInconclusive Evidence Among Studies That Met Our Inclusion Criteria\nFour studies evaluated the relationship of mental health–related prohibitions with suicide. These studies, which showed mixed but generally uncertain results, had serious or critical methodological issues that raise concerns about the reliability of their findings.\nNo Studies Meeting Our Inclusion Criteria\nAlthough mental illness is often discussed as a potential factor in mass shootings and police shootings, no studies meeting our inclusion criteria examined the associations between prohibitions related to mental illness and these outcomes. Other outcomes without studies have less clear relevance to these laws.\nAdditional Context\nEpidemiological evidence suggests that a diagnosis of mental illness alone has little relation to risk of interpersonal violence (Swanson et al., 2015), although this risk varies by specific psychiatric disorder and the presence of comorbidities. At the same time, research indicates that individuals with mental disorders are more likely to be victims than perpetrators of violence (Desmarais et al., 2014).\nResearch has also demonstrated a strong link between mental illness and suicide; it is estimated that between 47 percent and 74 percent of suicides are related to mental disorders (Li et al., 2011; Cavanagh et al., 2003). As with interpersonal violence, there is substantial variability in the strength of this association depending on which indicators of mental disorders are assessed.\nHowever, despite higher risk, the size of the population affected by existing prohibitions may be too small to meaningfully affect population-level suicide rates. Indeed, in a simulation study of the hypothetical effects of prohibiting firearm ownership for individuals with past psychiatric hospitalization in New York City, the authors estimated that 144,000 individuals would need to be disqualified from firearm possession to prevent one suicide (Keyes et al., 2019).\nProhibitions Associated with Mental Illness in Depth\nFederal law prohibits the possession or purchase of firearms by certain individuals who have been adjudicated as mentally ill (18 U.S.C. 922), [1] and, over the past 26 years, approximately 2,900 potential gun purchases per year have been denied at the background check stage as a result of this prohibition (Federal Bureau of Investigation, 2023f). [2] However, the total number of people covered by this exclusion is not known. In 2021, an estimated 57.8 million adults in the United States had some form of mental illness—defined as any "mental, behavioral, or emotional disorder in the past year" other than a developmental or substance use disorder (Substance Abuse and Mental Health Services Administration, 2022). Of these adults, 14.1 million suffer from a "serious mental illness" that results in substantial impairment in carrying out major life activities. Existing laws that prohibit those with adjudicated mental health conditions from accessing firearms affect a subset of individuals who likely fall into the "serious mental illness" category. Expanding such prohibitions has the potential to affect a much larger set of individuals who fall into the "any mental illness" category, although broadening the scope of mental health restrictions poses technological, coordination, and legal (i.e., privacy) challenges (Liu et al., 2013).\nIf individuals with mental illness present a higher violence risk to themselves or others compared with those without mental illness, then restricting their access to firearms should reduce suicides and homicides. The magnitude of these effects will depend primarily on the reliability of the screening process instituted to identify disqualifying mental health conditions, the size of the marginal population affected by the expanded prohibitions, and the likelihood of individuals in that population committing harm to others or to themselves.\nThe effects of expanding firearm prohibitions also likely depend on rates of firearm ownership and access among individuals who are newly disqualified from possessing or purchasing firearms, particularly in the absence of mechanisms to remove existing firearms from prohibited possessors . While reliable data on who owns firearms in the United States are limited, some studies suggest that there are comparable rates of ownership among individuals with and without more-common mental health conditions, diagnoses, or symptoms (Hullenaar et al., 2023; Perlis et al., 2022; Richards et al., 2021; Swanson et al., 2015). However, a limited body of research among population subgroups (e.g., military veterans, adolescents) has found that certain psychiatric disorders (e.g., conduct disorder, intermittent explosive disorder) may be associated with higher rates of gun carrying (Bossarte et al., 2021; Kagawa et al., 2019). Overall, this research suggests that a substantial number of people with psychiatric disorders or symptoms own or have access to firearms.\nEpidemiological evidence suggests that a diagnosis of mental illness alone has little relation to risk of interpersonal violence (Swanson et al., 2015); in particular, studies estimate that between 2\xa0percent and 4\xa0percent of all violent behavior may be attributable to mental illness (Corrigan and Watson, 2005; Swanson, 1994). While research shows that the risk of an individual perpetrating an act of violence varies by specific psychiatric disorder and the presence of comorbidities, few studies have examined firearm violence specifically (Whiting, Lichtenstein, and Fazel, 2021). One study found that among a sample of convicted murderers in Indiana, perpetrators with serious mental illness were significantly less likely to have used a firearm compared with other perpetrators (Matejkowski et al., 2014). A study of 82,000 individuals with mental illness in Florida showed that the arrest rate for violent crimes involving a firearm was the same among the study population as the estimated general population rate—approximately 215 arrests per 100,000 people (Swanson et al., 2016). Elevated rates of violence tend to be reported for involuntarily committed patients (Choe, Teplin, and Abram, 2008), but this population is already barred from acquiring firearms through existing federal mental health–related prohibitions. Overall, between 2001 and 2010, less than 5\xa0percent of the 120,000 firearm-related homicides in the United States were committed by individuals diagnosed with a mental illness (Metzl and MacLeish, 2015), suggesting that expanded prohibitions based on mental health status might be expected to affect less than 5\xa0percent of firearm crimes.\nThe potential relationship between mass shootings and mental illness is also unclear. Although media coverage often links mass shootings with serious mental illness (McGinty et al., 2016, 2014), an analysis of 173 mass shooting events between 2009 and 2017 (Everytown for Gun Safety Support Fund, 2018) reported that in only one incident (0.5\xa0percent) did the perpetrator have a history of mental illness that prohibited purchase of a firearm from a federally licensed dealer; however, a review of cases through 2015 (Fox and Fridel, 2016) found that formal concerns about the mental health of the perpetrator had been previously expressed for 15 cases (11.3\xa0percent), and informal concerns about the shooter\'s mental health had been previously expressed for 13 additional cases (9.8\xa0percent). Although mass public shooters are more likely to have a psychotic disorder compared with perpetrators of multiple-victim shootings related to familicide or profit motivation, the prevalence of severe mental illness among this subgroup is still quite low (Fox and Levin, 2015). A study of 106 perpetrators of mass public shootings in the United States between 1990 and 2014 found that less than 5\xa0percent of offenders had a history of involuntary commitment or adjudication of dangerousness that would have prohibited them from purchasing a firearm following the federal mental health background check (Silver, Simons, and Craun, 2018). A study of 575 perpetrators of mass shootings in the United States between 1970 and 2019 found that 8\xa0percent of offenders had a history of psychotic symptoms (e.g., delusions, thought disorganization, hallucinations) and 23\xa0percent of offenders had histories of symptoms of any psychiatric or severe neurologic disorder (Brucato et al., 2021). Counting less severe forms of mental illness, Follman, Aronsen, and Pan (2022) found that 62 of the 125 mass public shootings between 1982 and 2021 that were identified by Mother Jones magazine involved a shooter with a history of possible mental health problems.\nAt the same time, research indicates that individuals with mental disorders are more likely to be victims than perpetrators of violence (Desmarais et al., 2014). One study of persons with severe mental illness (in treatment at mental health agencies in Chicago) found that their annual exposure to violent crime victimization was more than four times higher than rates in the general population (Teplin et al., 2005). Another meta-analysis produced similar results, finding the prevalence of past-year violent victimization among individuals with mental illness to be 24\xa0percent (with estimates of the reviewed studies ranging from 7\xa0percent to 63\xa0percent) (Hughes et al., 2012). Extrapolating this estimate to the national population of individuals with serious mental illness in 2015 would suggest that approximately 2.3 million individuals with serious mental illness are victims of violent crime each year; however, this is likely an overestimate because most studies sampled individuals who were receiving inpatient or outpatient treatment for diagnosed psychiatric illnesses or focused on severe mental illnesses (such as schizophrenia) (Hughes et al., 2012). For instance, although the National Crime Victimization Survey does not collect information on mental health directly, its estimates suggest that there are about 780,000 cases 

In [10]:
df.columns

Index(['title', 'snippet', 'url', 'text'], dtype='object')

In [18]:
df.loc[12, 'text']

"Working Together to Reduce Black Maternal Mortality\nAt a glance\nBlack Maternal Health Week is recognized each year from April 11-17 to bring attention and action in improving Black maternal health. Everyone can play a role in working to prevent pregnancy-related deaths and improving maternal health outcomes.\nMost Pregnancy-Related Deaths are Preventable\nEach year in the United States, hundreds of people die during pregnancy or in the year after. Thousands more have unexpected outcomes of labor and delivery with serious short- or long-term health consequences. Every pregnancy-related death is tragic, especially because more than 80% of pregnancy-related deaths in the U.S. are preventable . Recognizing urgent maternal warning signs, providing timely treatment, and delivering respectful, quality care can prevent many pregnancy-related deaths.\nRacial Disparities Exist\nBlack women are three times more likely to die from a pregnancy-related cause than White women. Multiple factors contribute to these disparities, such as variation in quality healthcare, underlying chronic conditions, structural racism, and implicit bias. Social determinants of health prevent many people from racial and ethnic minority groups from having fair opportunities for economic, physical, and emotional health.\nWorking Together to Reduce Black Maternal Mortality\nDuring Black Maternal Health Week, learn how you can support pregnant people in your life to reduce factors that contribute to pregnancy-related complications and death.\nPregnant people and their families can:\nTalk to a healthcare provider if anything doesn't feel right or is concerning.\nKnow and seek immediate care if experiencing any of the urgent maternal warning signs , including severe headache, extreme swelling of hands or face, trouble breathing, heavy vaginal bleeding or discharge, overwhelming tiredness, and more. These symptoms could indicate a potentially life-threatening complication.\nShare recent pregnancy history during each medical care visit for up to one year after delivery.\nConnect with healthcare and social support systems before, during, and after pregnancy.\nHealthcare providers can:\nAsk questions to better understand their patient and things that may be affecting their lives.\nHelp patients, and those accompanying them, understand the urgent maternal warning signs and when to seek medical attention right away.\nHelp patients manage chronic conditions or conditions that may arise during pregnancy like hypertension , diabetes , or depression .\nRecognize and work to eliminate unconscious bias in themselves and in their office on an ongoing basis.\nRespond to any concerns patients may have.\nProvide all patients with respectful quality care.\nHospitals and healthcare systems can:\n"

In [3]:
import pandas as pd

df= pd.read_pickle("./PoliResult/out/grounding/closed_final_150_sample_llama-8b_grounded_direct_ruling_comments_V1.0.pkl")
df.loc[8, 'grounded_answers']

'\nThe article does not mention the speaker or author of the Instagram post. It only mentions that the post was flagged as part of Facebook\'s efforts to combat false news and misinformation on its news feed.\n\nHowever, it does mention that the claim in the post was debunked by PolitiFact, a fact-checking organization, which suggests that the claim is not credible. PolitiFact\'s credibility and expertise on the topic are established through their fact-checking work and partnership with Facebook.\nThe claim that the CDC finally admits its COVID-19 test can\'t tell the difference between the virus and the flu is a misinterpretation or exaggeration of the CDC\'s statement. According to the article, the CDC\'s original test was specifically designed to only detect SARS-CoV-2 viral genetic material and does not detect influenza or differentiate between influenza and SARS-CoV-2. The CDC\'s withdrawal of its request for emergency use authorization was due to the FDA\'s authorization of hundreds of other SARS-CoV-2 diagnostic tests that can test for multiple viruses at the same time.\nThe article does not mention a specific CDC statement or document from January 29, 2022. However, it does mention the following CDC statements and documents that support or contradict the claim:\n\n1. A lab alert issued by the CDC on July 21, which stated that the CDC was withdrawing its request to the FDA for emergency use authorization of the CDC 2019-Novel Coronavirus (2019-nCoV) Real-Time RT-PCR Diagnostic Panel.\n2. A clarification issued by the CDC on August 2, which stated that the change was because the FDA had authorized hundreds of other SARS-CoV-2 diagnostic tests, many of which can test for more than one illness at a time.\n3. A fact-check by PolitiFact on July 30, which found that the original CDC request was not for a physical test as the false claim suggested, but rather for a protocol for how to test for COVID-19.\n4. The instructions for use for the CDC\'s original panel, which "includes sensitivity data as well as specificity/exclusivity data regarding Influenza and other viruses."\nAccording to the article, the following credible sources confirm or deny the claim:\n\n1. PolitiFact: A fact-checking organization that debunked the claim in July and again in December, stating that the original CDC test was not designed to differentiate between the flu and COVID-19.\n2. The FDA: An FDA spokesman pointed to the instructions for use for the CDC\'s original panel, which includes sensitivity and specificity data regarding influenza and other viruses. This suggests that the original test was not designed to differentiate between the flu and COVID-19.\n3. The CDC\'s website: The CDC states that the original test "filled an important unmet need" in early 2020, but that newer tests that can detect both COVID-19 and influenza are more efficient.\n4. The CDC\'s lab alert: The CDC issued a lab alert on July 21, stating that it was withdrawing its request for emergency use authorization of the original test, and encouraging labs to use newer tests that can detect multiple viruses at the same time.\n\nThese sources confirm that the original CDC test was not designed to differentiate between the flu and COVID-19, and that the claim is false.\nThe claim that the CDC is withdrawing its PCR test for COVID-19 because it can\'t differentiate between the coronavirus and the flu is related to a specific issue surrounding the COVID-19 pandemic, specifically the transition to newer tests that can detect multiple viruses at the same time, particularly as the country heads into influenza season.\n\nThe context of the claim is that the CDC issued a lab alert on July 21, 2021, announcing the withdrawal of its request for emergency use authorization of the original PCR test, which was designed to only detect SARS-CoV-2 and not influenza. The CDC encouraged labs to use newer tests that can detect multiple viruses, including influenza, to save time and resources. This decision was made because the FDA had authorized hundreds of other SARS-CoV-2 diagnostic tests that can test for multiple illnesses at once.\nAccording to the article, the claim that the CDC\'s COVID-19 test can\'t tell the difference between the virus and the flu is not a recent development. The article states that the CDC had already clarified this issue in July 2021, when it issued a clarification after the initial alert raised questions. In the clarification, the CDC explained that the first diagnostic panel it had been seeking emergency authorization for "was specifically designed to only detect SARS-CoV-2 viral genetic material. It does not detect influenza or differentiate between influenza and SARS-CoV-2."\n\nAdditionally, the article mentions that PolitiFact had already fact-checked this claim in July 2021, finding that the original CDC request was not for a physical test as the false claim suggested, but rather for a protocol for how to test for COVID-19. This suggests that the issue had been discussed in the scientific community for some time before the recent resurgence of the claim.\nThe claim that the CDC is withdrawing its PCR test for COVID-19 because it can\'t differentiate between the coronavirus and the flu has several implications:\n\n1. **Misinformation and confusion**: The claim can lead to confusion among the public, healthcare providers, and policymakers, potentially causing them to question the accuracy of COVID-19 testing and the effectiveness of public health measures.\n2. **Delayed or reduced testing**: If people believe that the test is unreliable, they might be less likely to get tested, which can lead to delayed or reduced diagnosis and treatment of COVID-19 cases.\n3. **Inadequate public health response**: The claim can undermine trust in public health authorities and their recommendations, potentially leading to a decrease in adherence to guidelines, such as vaccination, mask-wearing, and social distancing.\n4. **Increased risk of flu and COVID-19 transmission**: If people are less likely to get tested or take preventive measures, they may be more likely to contract and spread both flu and COVID-19, potentially leading to increased morbidity and mortality.\n5. **Impact on healthcare resources**: The claim can lead to a surge in unnecessary testing and healthcare utilization, as people may seek alternative or unproven testing methods, which can strain healthcare resources and divert attention from evidence-based practices.\n\nIn terms of public health policy, testing protocols, or individual decisions related to COVID-19 and the flu, the claim can:\n\n1. **Undermine trust in public health authorities**: The claim can erode trust in the CDC and other public health agencies, making it more challenging to implement effective policies and guidelines.\n2. **Delay or hinder the development of new testing technologies**: The claim can create a false narrative that existing tests are flawed, potentially delaying the development and implementation of new, more accurate testing technologies.\n3. **Increase the risk of misinformation and disinformation**: The claim can contribute to the spread of misinformation and disinformation, which can have serious consequences for public health and individual well-being.\n\nOverall, the claim has significant implications for public health policy, testing protocols, and individual decisions related to COVID-19 and the flu, and it is essential to address and debunk this misinformation to ensure the effective management of these diseases.\nAccording to the article, there isn\'t a mention of any other similar claims or controversies surrounding the accuracy or reliability of COVID-19 tests. However, it does mention that the claim in question is part of a broader narrative of misinformation and false claims surrounding the COVID-19 pandemic.\n\nThe article states that the claim was debunked in July by PolitiFact and other fact-checkers, but it is back again, indicating that there may be a pattern of false information being spread and then resurfacing. The article also mentions that the claim may be cropping up again now due to the CDC\'s announcement that the withdrawal of the original test would be effective on Dec. 31, giving laboratories advance notice.\n\nIn the broader narrative, this claim fits into the category of misinformation and false claims surrounding the COVID-19 pandemic, which has been a significant issue during the pandemic. The article highlights the importance of fact-checking and clarifying information to combat misinformation and ensure that accurate information is available to the public.\nThe article does not explicitly state the speaker\'s or author\'s motivation for making this claim. However, based on the context and the fact-checking efforts mentioned, it can be inferred that the author\'s motivation is likely to debunk a false claim and provide accurate information.\n\nThe author appears to be a fact-checker or a journalist, as they mention PolitiFact\'s fact-checking efforts and provide clarification on the CDC\'s actions. The author\'s tone is neutral and informative, aiming to educate readers about the actual events surrounding the CDC\'s PCR test.\n\nAs for potential biases or agendas, it\'s possible that the author is motivated by a desire to counter misinformation and promote accurate information, which could be seen as a bias towards fact-based reporting. However, this bias is not necessarily a negative one, as it aims to promote critical thinking and informed decision-making.\n\nIt\'s also worth noting that the article does not provide any information that suggests the author has a personal stake or agenda in the matter. The author\'s primary goal appears to be providing accurate information and setting the record straight about the CDC\'s actions.\nAccording to the article, there are alternative explanations or interpretations of the CDC\'s statement that might clarify or contradict the claim. \n\n1. The CDC\'s withdrawal of the original test was not because it couldn\'t differentiate between COVID-19 and the flu, but because the FDA had authorized hundreds of other SARS-CoV-2 diagnostic tests that can test for multiple viruses at the same time.\n\n2. The original test was specifically designed to only detect SARS-CoV-2 viral genetic material and did not detect influenza or differentiate between influenza and SARS-CoV-2.\n\n3. The CDC had also sought emergency use authorization for its Influenza SARS-CoV-2 (Flu SC2) Multiplex Assay that could test for both viruses, which the FDA soon granted.\n\n4. The CDC\'s statement that the withdrawal would be effective on Dec. 31 was to give laboratories advance notice, not because the test was being withdrawn due to its inability to differentiate between COVID-19 and the flu.\n\nThese alternative explanations and interpretations contradict the claim that the CDC was withdrawing its PCR test for COVID-19 because it couldn\'t differentiate between COVID-19 and the flu.\nYes, the CDC has issued a clarification regarding the claim. According to the article, the CDC issued a clarification on August 2, stating that the change was because the FDA had authorized hundreds of other SARS-CoV-2 diagnostic tests, many of which can test for more than one illness at a time.\n\nThe CDC also clarified that the original diagnostic panel it had been seeking emergency authorization for was specifically designed to only detect SARS-CoV-2 viral genetic material and does not detect influenza or differentiate between influenza and SARS-CoV-2.\n\nAdditionally, PolitiFact found that the original CDC request was not for a physical test, but rather for a protocol for how to test for COVID-19. The CDC had also sought emergency use authorization earlier in July for its Influenza SARS-CoV-2 (Flu SC2) Multiplex Assay that could test for both viruses, which the FDA soon granted.\n\nThe current understanding of the issue is that the CDC is withdrawing its request for emergency use authorization of the original PCR test because newer tests that can detect multiple viruses at the same time are available and more efficient.\nAccording to the article, the potential consequences of spreading misinformation or exaggerating the claim include:\n\n1. **Undermining public trust**: The repeated spread of false information can lead to a loss of trust in health authorities, such as the CDC, and scientific institutions. This can have serious consequences, as people may become skeptical of important health advice and guidelines.\n2. **Misinformation can cause confusion**: The article highlights how the false claim was initially debunked but resurfaced again. This can cause confusion among the public, making it difficult for people to distinguish between fact and fiction.\n3. **Delayed or incorrect health decisions**: If people believe the false claim, they may delay or forego important health measures, such as getting tested or vaccinated, which can have serious consequences for their health and the health of those around them.\n4. **Erosion of credibility**: The repeated spread of misinformation can erode the credibility of fact-checkers, journalists, and other trusted sources of information, making it harder for them to effectively combat misinformation in the future.\n\nThe article suggests that the consequences of spreading misinformation can be severe, and it\'s essential to address these issues promptly to maintain public trust in health authorities and scientific institutions.\nAccording to the article, there are no similar claims or controversies surrounding the accuracy or reliability of COVID-19 tests mentioned. However, it does mention that the claim in question is part of a broader narrative of misinformation and false claims surrounding COVID-19 tests.\n\nThe article states that "This past summer, many social media posts claimed that the CDC was withdrawing its PCR test for COVID-19 because the test didn’t differentiate the coronavirus and the flu." This suggests that there may be a pattern of misinformation and false claims surrounding COVID-19 tests, but it does not provide any further information on similar claims or controversies.\n\nIt\'s worth noting that the article does mention that the CDC had sought emergency use authorization for its Influenza SARS-CoV-2 (Flu SC2) Multiplex Assay, which could test for both COVID-19 and influenza, and that the FDA soon granted this authorization. This suggests that there may be some controversy or debate surrounding the use of different types of COVID-19 tests, but it is not clear if this is a broader narrative or a specific issue.\nAccording to the article, the current state of knowledge regarding the differences between COVID-19 and the flu is that the original CDC test for COVID-19, the "CDC 2019-Novel Coronavirus (2019-nCoV) Real-Time RT-PCR Diagnostic Panel," was specifically designed to only detect SARS-CoV-2 viral genetic material and does not detect influenza or differentiate between influenza and SARS-CoV-2.\n\nThe article also states that the CDC\'s Influenza SARS-CoV-2 (Flu SC2) Multiplex Assay, which was granted emergency use authorization by the FDA, can test for both viruses. This suggests that newer tests can distinguish between COVID-19 and the flu.\n\nAdditionally, the article mentions that the original test\'s instructions for use include sensitivity data as well as specificity/exclusivity data regarding Influenza and other viruses, implying that there is a way to differentiate between the two.\n\nOverall, the article suggests that health authorities and scientists can distinguish between COVID-19 and the flu using newer tests that can detect multiple viruses at the same time, and that the original CDC test was not capable of differentiating between the two.\nAccording to the article, the CDC\'s plan to withdraw its original PCR test for COVID-19 was not due to a lack of specificity or accuracy, but rather because the FDA had authorized hundreds of other SARS-CoV-2 diagnostic tests that can test for multiple viruses at the same time, including influenza.\n\nThe article also mentions that the CDC had sought emergency use authorization for its Influenza SARS-CoV-2 (Flu SC2) Multiplex Assay, which can test for both viruses, and that the FDA soon granted this authorization. This suggests that the CDC is actively working to improve the accuracy and specificity of COVID-19 tests by developing and authorizing newer tests that can detect multiple viruses at the same time.\n\nIn this context, the claim that the CDC is withdrawing its PCR test for COVID-19 because it can\'t differentiate between the flu and COVID-19 is not only false but also outdated, as the CDC has already moved on to newer tests that can detect multiple viruses simultaneously.\nThe speaker or author appears to be a journalist or a fact-checker, as they are referencing a PolitiFact fact-check and an email from an FDA spokesman. They are also quoting directly from the CDC\'s website and lab alerts, which suggests that they have access to official information and statements from the CDC.\n\nGiven their role as a journalist or fact-checker, it\'s likely that their relationship with the CDC or other health organizations is that of an observer or reporter, rather than a direct participant or employee. This might influence their perspective or interpretation of the claim in a few ways:\n\n1. They may be more likely to rely on official sources and statements from the CDC, which could be seen as a more authoritative or trustworthy source of information.\n2. They may be more inclined to debunk or correct claims that are based on misinformation or misunderstandings, as their role is to provide accurate and factual information to the public.\n3. They may have a more nuanced understanding of the complexities and nuances of the issue, as they are likely to have access to a wider range of information and perspectives.\n\nHowever, it\'s worth noting that the article does not suggest any bias or conflict of interest on the part of the author or speaker. Their goal appears to be providing accurate information and correcting misinformation, rather than promoting a particular agenda or perspective.\nThere are a few relevant facts and context that might shed light on the claim. \n\n1. The claim has been debunked before: PolitiFact debunked the claim in July, indicating that the person or group making the claim may be aware of the fact-check but is choosing to repeat it anyway.\n\n2. The claim is being repeated despite the CDC\'s clarification: The CDC issued a clarification on August 2, explaining the reason behind the withdrawal of the original test. Despite this, the claim is still being repeated, suggesting that the person or group making the claim may be intentionally spreading misinformation.\n\n3. The claim is being repeated on social media: The claim is being repeated on social media platforms, including Instagram, which suggests that the person or group making the claim may be using social media to spread misinformation to a wider audience.\n\n4. The claim may be related to a specific agenda or ideology: The fact that the claim is being repeated despite being debunked suggests that the person or group making the claim may have a specific agenda or ideology that they are trying to promote. However, this is speculative and not explicitly stated in the article.\n\n5. The claim may be related to a lack of understanding of the topic: The fact that the claim is being repeated despite the CDC\'s clarification suggests that the person or group making the claim may not have a good understanding of the topic or may be intentionally misrepresenting the facts.\nThe claim that the CDC was withdrawing its PCR test for COVID-19 because it couldn\'t differentiate between the coronavirus and the flu is a misleading one. In reality, the CDC was withdrawing its request for emergency use authorization of a s

In [19]:
import pandas as pd
import json

with open ("./PoliResult/out/aggregate/temp_0_150_sample_llama-8b_aggregate_direct_ruling_comments_V1.0.json") as f:
    agg1= json.load(f)

print(type(agg1))
print(len(agg1))

<class 'list'>
88

In [20]:


print(type(agg1))

<class 'list'>

In [21]:
with open ("./PoliResult/out/aggregate/temp_89_150_sample_llama-8b_aggregate_direct_ruling_comments_V1.0.json") as f:
    agg2= json.load(f)

print(type(agg2))
print(len(agg2))

<class 'list'>
61

In [22]:
agg1.extend(agg2)
print(len(agg1))

149

In [23]:
with open("./PoliResult/out/aggregate/final0_150_sample_llama-8b_aggregate_direct_ruling_comments_V1.0.json", "w") as f:
    json.dump(agg1, f)

In [24]:
import pandas as pd

df= pd.read_json("PoliResult/out/aggregate/final0_start_150_sample_llama-8b_aggregate_direct_V1.0.json")
df

,id,label,claim,grounded_answers,agg_response
0,TUD98,FALSE,The United Nations plans to implant everyone w...,\nThe article does not provide information abo...,[HALF-TRUE]\n\nThe article provides evidence t...
1,TUD44,TRUE,The Machinists Union does not (support the USM...,\nThe article does not mention a specific date...,Claim: The Machinists Union does not (support ...
2,TUD62,FALSE,Gov. Tony Evers proposed raising taxes on the ...,\nJohn Nygren is a state representative and th...,Claim: Gov. Tony Evers proposed raising taxes ...
3,TUD24,TRUE,"If you're a black woman, you're 320% more like...",\nThe specific source of Andrew Yang's claim i...,[TRUE]\n\nThe article provides evidence that A...
4,TUD102,FALSE,Left-wing activist John Sullivan incited (the)...,\nThe speaker/source of the claim that John Su...,[HALF-TRUE]\n\nThe article presents a nuanced ...
...,...,...,...,...,...
144,TUD67,TRUE,Confederate veterans were conferred with many ...,\nSid Miller is the Texas Agriculture Commissi...,Claim: Confederate veterans were conferred wit...
145,TUD117,FALSE,Electromagnetic radiation from wireless techno...,\nThe article does not provide detailed inform...,[HALF-TRUE]\n\nThe article provides evidence t...
146,TUD47,TRUE,"Over the past two years, climate and weather d...","\nAccording to the article, Tammy Baldwin is a...","Claim: Over the past two years, climate and we..."
147,TUD153,HALF TRUE,"One in eight American adults, or 12.7 percent ...","\nAccording to the article, Richard Ojeda is a...",[HALF-TRUE]\n\nThe claim made by Richard Ojeda...
148,TUD154,HALF TRUE,California is leading the nation in holding dr...,"\nAccording to the article, Gavin Newsom is th...",[HALF-TRUE]\n\nJustification: \nThe claim that...

In [25]:
df.to_csv("llama_direct_agg.csv")

In [7]:
def question_extraction_llama(question_df, prompt_strategy):
    #print("in function")
    if prompt_strategy == 'direct':
        question_df['response'] = question_df['response'].apply(lambda x: (x.split('Followup Question: '))[1::])
        
    elif prompt_strategy == 'fewshot':
        #print("in elif")
        for i in range(len(question_df)):
            #print("in loop")
            s = question_df.loc[i, 'response']
            s= s.split('**\n')[-1]
            s= s.split('\n')
            #print(s)
            question_df.loc[i, 'response']= s

    elif prompt_strategy == 'novice_questions':
        question_df['response'] = question_df['response'].apply(lambda x: (x.split('Followup Question: '))[1::])

    elif prompt_strategy == 'journalist_questions':
        question_df['response'] = question_df['response'].apply(lambda x: (x.split('Followup Question: '))[1::])

    return question_df

In [8]:
direct_q= pd.read_json("PoliResult/out/decompose/final0_start_150_sample_llama-8b_decompose_direct_V1.0.json")
df = question_extraction_llama(direct_q, "direct")
df

,id,label,claim,response,context,justification
0,TUD98,FALSE,The United Nations plans to implant everyone w...,[What is the credibility of the bloggers makin...,What’s more wild than science fiction’s robots...,This theory is an overreach of a system the Un...
1,TUD44,TRUE,The Machinists Union does not (support the USM...,[What is the context of the statement made by ...,In the last debate before the Feb. 3 Iowa pres...,"Sanders said about supporting USMCA, ""The AFL-..."
2,TUD62,FALSE,Gov. Tony Evers proposed raising taxes on the ...,"[Who is John Nygren, and what is his position ...",Wisconsin's struggling farms were front and ce...,Nygren said the governor proposed raising taxe...
3,TUD24,TRUE,"If you're a black woman, you're 320% more like...",[What is the specific source of Andrew Yang's ...,In an exchange about racial inequality at Dece...,Yang said black women are 320% more likely to ...
4,TUD102,FALSE,Left-wing activist John Sullivan incited (the)...,"[Who is the speaker/source of the claim, and w...","UPDATE, Jan. 15, 2021: Following the publicati...","A Facebook post claimed Sullivan ""incited (the..."
...,...,...,...,...,...,...
145,TUD67,TRUE,Confederate veterans were conferred with many ...,"[Who is Sid Miller, and what is his position o...",Texas Agriculture Commissioner Sid Miller wade...,"Miller said: ""Confederate veterans were confer..."
146,TUD117,FALSE,Electromagnetic radiation from wireless techno...,[What is the speaker's background and qualific...,"Since the beginning of the pandemic, various a...",A blog post claims that a study found clear ev...
147,TUD47,TRUE,"Over the past two years, climate and weather d...",[Who is Tammy Baldwin and what is her position...,"When it comes to weather and climate change, t...","Baldwin said ""Over the past two years, climate..."
148,TUD153,HALF TRUE,"One in eight American adults, or 12.7 percent ...","[Who is Richard Ojeda, and what is his experti...","Richard Ojeda, the former West Virginia legisl...","Ojeda tweeted, ""One in eight American adults, ..."
149,TUD154,HALF TRUE,California is leading the nation in holding dr...,"[Who is Gavin Newsom, and what is his position...",California regularly portrays itself as a nati...,"Newsom said ""California is leading the nation ..."

In [12]:
df['#questions']= df['response'].apply(lambda x: len(x))

In [20]:
print(df['#questions'].mean(), df['#questions'].std())

56.3 49.17312929126335

In [19]:
fewshot_q= pd.read_json("PoliResult/out/decompose/final0_start_150_sample_llama-8b_decompose_fewshot_V1.0.json")
df1 = question_extraction_llama(fewshot_q, "fewshot")
df1['#questions']= df1['response'].apply(lambda x: len(x))
print(df1['#questions'].mean(), df1['#questions'].std())

8.593333333333334 7.711315373363486